### ISSUE TITLE
Centralize all the badge and category links

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-cookbook#111]
Is there any way we could avoid repeating the same badge and category links on every page that uses them? Perhaps a central file of links that gets included via some mdBook magic into every page?

For example these are repeated on 4 pages so far:

```
[cat-encoding-badge]: https://img.shields.io/badge/-encoding-red.svg
[cat-encoding]: https://crates.io/categories/encoding
```

This is tedious and error-prone on every new example we add.

**Comment by dtolnay** [comment]
Relevant mdBook issue: https://github.com/azerupi/mdBook/issues/245

**Comment by budziq** [comment]
no longer blocked after mdbook update.
now we can use `{{include links.md}}` clauses
