### ISSUE TITLE
RFC - add "copy to clipboard" / "download" button to each recipe

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#171]
It would be nice
to have button allowing user to copy whole recipe to clipboard and possibly an additional one to download it as an rs file.

Most likely the buttons would be located next to expand button but visible only on hover or via popup selector to avoid clobbering the interface.

Most likely it is an issue for mdbook itself as we would need changes on per snippet rendering. 
cc @azerupi

**Comment by budziq** [comment]
hmm possible implementation might be based on https://clipboardjs.com

**Comment by brson** [comment]
Yeah that would be great. The instructions for turning examples into cargo projects are pretty complex now. Would be great to be a oneliner.

Another possibility would be to use something like [cargo-script](https://github.com/DanielKeep/cargo-script) to put all the dependencies inside the example itself, so users could avoid the matter of creating a Cargo.toml file when experimenting with the examples.

**Comment by budziq** [comment]
> Yeah that would be great. The instructions for turning examples into cargo projects are pretty complex now. Would be great to be a oneliner.

@brson I guess that you are referring to the second idea ("download button"). I've originally meant it as an extension to the "copy to clipboard". I understand that you are suggesting a usecase in which user would download a whole bootstrap for a project (Cargo.toml + main.rs). This is very interesting but would be much more involved. 

And what is your opinion on the "copy to clipboard" button?

**Comment by budziq** [comment]
Clipboard handling has been merged to mdbook https://github.com/azerupi/mdBook/pull/303 It will work out of the box on next release but  will require an update of our custom book.css to have functionality (notification popup). Will close this after update.

**Comment by budziq** [comment]
clipboard support added with update of mdbook
