### ISSUE TITLE
Cookbook ideas for same-file crate

### ISSUE THREAD

**Issue by KodrAus** [rust-lang-nursery/rust-cookbook#205]
Come up with ideas for nice introductory examples of using `same-file`, possibly in combination with other crates, that would be good to show in the Rust Cookbook. Please leave a comment here with your ideas! You don't necessarily have to write the example code yourself but PRs are always welcome!

edit:
- [x] ["avoid writing to a file you are reading from"](https://github.com/brson/rust-cookbook/issues/206)
- [x] ["find loops in filesystem"](https://github.com/brson/rust-cookbook/issues/207)

**Comment by KodrAus** [comment]
This is a simple crate with some examples [in the `same-file` repo](https://github.com/BurntSushi/same-file/tree/master/examples).

**Comment by budziq** [comment]
how about?:
- "avoid writing to a file you are reading from"
    - or a variant "check if stdout is not redirected to file you are reading from"
- "find loops in filesystem"

**Comment by alisha17** [comment]
I would like to write examples for this. Well, where should I start from?

**Comment by budziq** [comment]
@alisha17 I'm still soliciting ideas for this crate. If @KodrAus gives a :+1: for my 2 ideas above then I'll create issues for them with explanations and you are ready to go.

**Comment by KodrAus** [comment]
@budziq I think those are great examples!

**Comment by budziq** [comment]
@alisha17 you are good to go with any of the two listed examples. Ping me If you'll have any questions.

**Comment by budziq** [comment]
all ideas implemented so closing for now
