### ISSUE TITLE
"avoid writing to a file you are reading from"

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#206]
Use the [same-file](https://github.com/BurntSushi/same-file/) crate to write an example testing if application is not trying to read and write to the same file.

One such example would be if stdout/stderr would be redirected to a file
```bash
./my_app 1 > output.txt
```
while `my_app` would open and read from such file modify read lines in some ways and write them to stdout 

Another example would be if application would check if `infile` is not a symlink to `outfile`

cc https://github.com/brson/rust-cookbook/issues/205

**Comment by alisha17** [comment]
What will be the best approach if I would want to check if infile is not a symlink to outfile using same-file crate?

**Comment by budziq** [comment]
please see the crate examples https://github.com/BurntSushi/same-file/tree/master/examples the api surface is quite small.

I would like this exampke to contain both approaches (is_same_file and Handle).

we would split this example to two separate code snippets.

- Handle approach for checking if file we are reading from file to which the stdout is redirected to
- is_same_file for checking if infile and out file are not symlinked

**Comment by alisha17** [comment]
Is there a way to easily redirect stdout to a file?
Also, the file passed for the write operation will simply be the file descriptor of the file opened for reading?

**Comment by budziq** [comment]
> Is there a way to easily redirect stdout to a file?

Yep. Just the way I've shown previously:
`./my_app  > output.txt`

Most unix shells support this syntax and as far as I know windows batch does as well.
But it might be easier to illustrate with stderr (then you will be able to print out some messages without it getting redirected to a file)
`./my_app 2 > output.txt`

> Also, the file passed for the write operation will simply be the file descriptor of the file opened for reading?

Right. when stdin, stdout or stderr are redirected to/from a file these have the same fd in the context of given process. The `same-file` crate gives a high level wrapper around this behavior (and few other heuristics).

**Comment by alisha17** [comment]
I am not much familiar with how this must be implemented. I know it's definitely very trivial but I am a bit confused. :/ @budziq

**Comment by alisha17** [comment]
Can you describe a simple workflow for this? I know this is pretty trivial. But I am somewhat confused how effectively can the API of same_file can be effectively used here?

**Comment by budziq** [comment]
Try to think how you could turn this example https://github.com/BurntSushi/same-file/blob/master/examples/is_stderr.rs into an even simpler one. 

- open a text file for reading
- check if the file you are opening to read from is not `Handle::stdout`
    - if yes print some error to stderr and bailout
    - if not printout the file lines with `println!`  with some minimal modification or filtering not to make this example artificial

**Comment by alisha17** [comment]
Thanks @budziq 
I will proceed with it.

**Comment by alisha17** [comment]
Under which section in the cookbook should the examples be added; in 'Basics'?

**Comment by budziq** [comment]
@alisha17 
> Under which section in the cookbook should the examples be added; in 'Basics'? @budziq

This example feel more like an "Aplication development". But It's pretty simple so we would put is somewhere early on the list.

> Also, these are two different code snippets, I should create different PRs for them?

nope no need to artificially split the work.

**Comment by alisha17** [comment]
fn run() -> io::Result<()> {
    let path_to_read = Path::new("hello.txt");

    let mut file = match File::open(&path_to_read) {
        Err(why) => panic!("couldn't open due to: {}", why.description()),
        Ok(file) => file,
    };

    let mut s = String::new();

    match file.read_to_string(&mut s) {
        Err(why) => panic!("couldn't read due to: {}", why.description()),
        Ok(_) => {},
    }
    
     let stderr_handle = Handle::stderr()?;
     let handle = Handle::from_path(path_to_read)?;

     if stderr_handle == handle {
        println!("You are reading and writing to the same file {:?}", path_to_read);
     } else {
        println!("The file contents are: \n {:?}",s);
     }      

     Ok(())
}

This is the code. When I run with cargo run 2> hello.txt, it will output "You are reading and writing to the same file "hello.txt"",otherwise the else case.
However if replace the println! with :
writeln!(&mut stderr, "You are reading and writing to same file :{}",path_to_read ).expect("Could not write to stderr");
It doesn't work as expected.
@budziq

**Comment by budziq** [comment]
@alisha17 then please create a minimal problematic snippet and describe what would be the expected behaviour. Cursory check show that the lib works as expected but there might some bug that I am missing and we might have to issue a bugreport to the samefile repo ;)

**Comment by alisha17** [comment]
@budziq I should create a code snippet and place it in a cookbook although it is not working as expected?

**Comment by budziq** [comment]
@alisha17 
> It doesn't work as expected.

As I've written beafore. The code (although requiring cleanup) looks and works as expected. If you feel that there is something wrong. Lets get to the bottom o this :smiley: Please:
- write what are your expectations (how the code should behave and what should be the output)
- what are you seeing instead

There are three possibilities here:
- there is a misconception on how this code should work (but you will have to give the description first)
- there is a bug in the library (that I am missing and/or  unable to reproduce. Then we will post a bug report in the library repo)
- the library docs are unclear leading you to misunderstand what is going on or the api can be used incorrectly (then we will also post a bug in their repo)

**Comment by alisha17** [comment]
@budziq Maybe I was not clear with my question. Where should I write the code snippet? Here itself?

**Comment by budziq** [comment]
I would just submit a PR and we will work on the form in standard review form. 
But still I would like to hear about the problem that you have mentioned.

**Comment by budziq** [comment]
hi @alisha17 do you need any assistance with this example?

**Comment by alisha17** [comment]
I have some doubts @budziq . Sorry, I lost my code. I will update in the comment tomorrow.

**Comment by budziq** [comment]
No problem. Take your time :)

**Comment by alisha17** [comment]
@budziq   Could you please have a look at this: https://gist.github.com/alisha17/902af5d034d91ef99ed9e2236d826f17? Is this correct in a way of what is expected in this recipe?

**Comment by budziq** [comment]
Yep pretty much :)

few notes. I would:
- remove the explicit `panic!`s and just use `?`
- change `Handle::stderr()` to `Handle::stdout()`
- run the example with `cargo run > hello.txt ` instead of `cargo run 2> hello.txt` 
- use `eprintln!` instead of `println!` to write to stderr
- make the same_file check before reading  form hello.txt to make the example more realistic
- `println!` all lines from hello.txt with some transformation (to_lower, some filter or whatever) to make the example more realistic

**Comment by alisha17** [comment]
@budziq  Can you please have a look at it now? https://gist.github.com/alisha17/902af5d034d91ef99ed9e2236d826f17 
And provide feedback

**Comment by budziq** [comment]
@alisha17 
few notes about the gist:
- no need to open and read file if we know that the situation is erroneous. We should just leave `bail!` 
- the `s` string is read after it is printed out ;)
- I would prefer for the printing / transform be done on a line basis like below

I would propose following snippet:
```rust
#[macro_use]
extern crate error_chain;
extern crate same_file;

use same_file::Handle;
use std::path::Path;
use std::fs::File;
use std::io::{BufRead, BufReader};

error_chain! {
     foreign_links {
          IOError(::std::io::Error);
     }
 }

fn run() -> Result<()> {
    let path_to_read = Path::new("new.txt");

    let stdout_handle = Handle::stdout()?;
    let handle = Handle::from_path(path_to_read)?;

    if stdout_handle == handle {
        bail!("You are reading and writing to the same file");
    } else {
        let file = File::open(&path_to_read)?;
        let file = BufReader::new(file);
        for (num, line) in file.lines().enumerate() {
            println!("{} : {}", num, line?.to_uppercase());
        }
    }

    Ok(())
}
quick_main!(run);
```

The example runs should be as follows:
- for ok version
```bash
cargo run
```
- for version presenting the actual error handling. please note the double `>>`. This avoids clobbering the file if we error out
```bash
cargo run >> ./new.txt
```
The version with `BufferedReader` line processing is nice in that it would run infinitely (appending to the file and reading from it) if there was no check for reading and writing to the same file.

**Comment by alisha17** [comment]
@budziq  Created PR for this. Thanks for your efforts with me. :)
