### ISSUE TITLE
Cookbook should probably be CC0 licensed

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rust-cookbook#209]
Since the content of the cookbook is intended to be copied freely, it would be better licensed CC0, with basically no restrictions.

Edit:

------------
We will track here the consent of all contributors (the list will be periodically updated):
Please drop a comment **here** if you consent or disagree.  [Link to CC0 license](https://creativecommons.org/choose/zero/). Once we gather consent following will be merged #210

- [x] @AlexEne
- [x] @AndyGauge
- [x] @CJStadler
- [x] @CrockAgile
- [x] @FaultyRAM
- [x] @Fierthraix 
- [x] @Lapz 
- [x] @Michael-F-Bryan
- [x] @Ophirr33
- [x] @Phaiax
- [x] @Piripant
- [x] @V1shvesh
- [x] @Wilfred
- [x] @alexcrichton
- [x] @alisha17
- [x] @badboy
- [x] @bjnyfv
- [x] @bobbo
- [x] @bostelk
- [x] @brson
- [x] @budziq
- [x] @cetra3
- [x] @charlesetc
- [x] @crypto-universe
- [x] @cschneid 
- [x] @derekdreery
- [x] @dhardy
- [x] @dhharris
- [x] @glennsl
- [x] @gsquire
- [x] @hegza 
- [x] @j-haj
- [x] @jaemk
- [x] @jbolila
- [x] @jeanm
- [x] @jmcomets
- [x] @jonashagstedt
- [x] @jrakow 
- [x] @lilianmoraru
- [x] @lucasem
- [x] @ludwigpacifici
- [x] @luisbg
- [x] @luser
- [x] @matklad
- [x] @mikeastock
- [x] @mykalu
- [x] @nocduro
- [x] @pepyakin
- [x] @pitdicker 
- [x] @portal-chan
- [x] @rap2hpoutre
- [x] @rofrol
- [x] @sb89
- [x] @skierpage 
- [x] @sotocodes 
- [x] @tyoc213
- [x] @yandexx

**Comment by abitrolly** [comment]
It is not possible to change existing license without asking all contributors if they agree to that. We can also assume that they didn't care in the first place..

**Comment by budziq** [comment]
We are planning to ask all contributors (at least above typo fix ones) for their consent. At the moment we are blocked with this mostly due to lack of time.

**Comment by Ophirr33** [comment]
Is this the right place to give consent? If so, my consent is given.

**Comment by dhardy** [comment]
[Link to CC0](https://creativecommons.org/choose/zero/)

**Comment by j-haj** [comment]
I agree

**Comment by yandexx** [comment]
I agree.

**Comment by charlesetc** [comment]
I agree!

**Comment by Michael-F-Bryan** [comment]
I consent

**Comment by budziq** [comment]
darn api pagination I'll add the other half of contributors later today 😞

**Comment by bjnyfv** [comment]
Fine with me!

**Comment by luisbg** [comment]
Sounds great to me 😄

**Comment by rap2hpoutre** [comment]
I consent

**Comment by Piripant** [comment]
This is great, I am happy to consent!

**Comment by AndyGauge** [comment]
I give permission for this license change.  Additionally I give unlimited consent to future licensing changes as the maintainers see fit.

**Comment by ludwigpacifici** [comment]
I agree

**Comment by mikeastock** [comment]
No problem from me!

**Comment by bobbo** [comment]
Fine with me

**Comment by gsquire** [comment]
You have my consent.

**Comment by bostelk** [comment]
I agree.

**Comment by jmcomets** [comment]
No problem on my side!

**Comment by sb89** [comment]
Fine with me.

**Comment by pepyakin** [comment]
I agree 👍

**Comment by mykalu** [comment]
Sounds great!

**Comment by jbolila** [comment]
I agree.

**Comment by V1shvesh** [comment]
I got no problems!

**Comment by portal-chan** [comment]
sounds good to me

**Comment by nocduro** [comment]
Sounds good 👍

**Comment by lucasem** [comment]
👍

**Comment by crypto-universe** [comment]
Sure, no problem :)

**Comment by Wilfred** [comment]
Fine by me.

**Comment by matklad** [comment]
I agree.

👍

**Comment by dhharris** [comment]
Sure

**Comment by lilianmoraru** [comment]
👍

**Comment by cetra3** [comment]
👍

**Comment by Phaiax** [comment]
I agree.

**Comment by glennsl** [comment]
I consent

**Comment by jeanm** [comment]
Sure

**Comment by luser** [comment]
I consent. (I love CC0!)

**Comment by FaultyRAM** [comment]
👍 I agree

**Comment by alisha17** [comment]
I agree!

**Comment by jonashagstedt** [comment]
I agree

**Comment by rofrol** [comment]
I agree

**Comment by derekdreery** [comment]
I consent

**Comment by AlexEne** [comment]
I agree.

**Comment by badboy** [comment]
I consent.

**Comment by jaemk** [comment]
I consent.

**Comment by hegza** [comment]
I consent!

**Comment by tyoc213** [comment]
Oh my.... I normally dont read some mails I just was curiost, didnt remember.

I consent!

**Comment by CJStadler** [comment]
I consent.

**Comment by dtolnay** [comment]
I give my consent.

**Comment by sotocodes** [comment]
👍 
I consent

**Comment by cschneid** [comment]
My change #353, and any other changes I make can be (re)licensed as CC0

**Comment by ericho** [comment]
I agree :smile:
(On vacations, sorry for the delay)

**Comment by branderson** [comment]
I consent

**Comment by Lapz** [comment]
I consent

**Comment by CrockAgile** [comment]
I consent 🎆

**Comment by pduzinki** [comment]
I consent

**Comment by baishuai** [comment]
I consent

**Comment by tshepang** [comment]
I consent

**Comment by thibaultbarbie** [comment]
I consent

**Comment by anna-liao** [comment]
I consent

**Comment by paulirotta** [comment]
I agree

**Comment by techtonik** [comment]
So, it is only @trentspi and @Yamakaky left in 2018 to agree on CC0 licensing for the cookbook.

What about new users from Jul 1, 2017?

**Comment by budziq** [comment]
> only @trentspi and @Yamakaky left 

Yep, sadly I was unable to reach them sofar.

> What about new users from Jul 1, 2017?

@techtonik this list is continuously updated with new contributors.

**Comment by trentspi** [comment]
I agree. Sorry for late response

**Comment by budziq** [comment]
> Sorry for late response

No worries :) We are almost go on the license change.

**Comment by jrakow** [comment]
I consent.

**Comment by skierpage** [comment]
I consent.

**Comment by Fierthraix** [comment]
I consent.

**Comment by pitdicker** [comment]
I consent.

**Comment by budziq** [comment]
Thanks all! Ping @Yamakaky
