### ISSUE TITLE
cookbook ideas for glob crate

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#211]
Come up with ideas for nice introductory examples of using [glob](https://crates.io/crates/glob), possibly in combination with other crates, that would be good to show in the Rust Cookbook. Please leave a comment here with your ideas! You don't necessarily have to write the example code yourself but PRs are always welcome!

The ideas should be very short and simple (not to collide with walkdir crate examples).
Most likely 1-2 examples will suffice

- [x] [find all png files recursively](https://github.com/brson/rust-cookbook/issues/218)
- [x] [find all files with given pattern ignoring filename case](https://github.com/brson/rust-cookbook/issues/219)
- [ ] ???

**Comment by budziq** [comment]
possible ideas:
- find all png files recursively
- find all files with given pattern ignoring filename case.

**Comment by brson** [comment]
Those ideas sound fine to me! I've filed the issues and will post to twir.
