### ISSUE TITLE
add "Avoid discarding errors during error conversions" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#215]
A slightly more complex example than https://github.com/brson/rust-cookbook/issues/214 showing aggregation of custom and crate errors that might use chain_err

Example should show off error-chain crate

cc https://github.com/brson/rust-cookbook/issues/184

**Comment by ludwigpacifici** [comment]
Hello @budziq 

Once  #325 is done, I can have a look at this one?

**Comment by ludwigpacifici** [comment]
I was thinking to create a specific error (i.e. impl `Error` trait) for the recipe. Then do a bad GET request via `reqwest` and use chain_err to append the recipe error on top of the `reqwest` error.

Is this basic idea good enough to highlight this issue?

**Comment by budziq** [comment]
Thanks for taking this on!

The idea is to get a semi complex error scenario ie. a single function returning 2-3 distinct error types and after it executes just [match on them](https://rust-lang-nursery.github.io/error-chain/error_chain/index.html#matching-errors).

There should be no need for creating any error types "by hand" here (I'd leave such information to RBE and TRPL).

**Comment by ludwigpacifici** [comment]
Ah thanks for the clarifications! I'll think about another idea.

**Comment by budziq** [comment]
This is basically a subset of your previous example but with match at the end instead of a backtrace and with no requirement about number of functions in the error stack. So `run` with 2-3 possible errors will suffice but I would suggest to use single user defined errors (within the `quick_main!`) and 1-2 foreign links.

**Comment by ludwigpacifici** [comment]
I got an example: do a `get` of an [url](
https://www.random.org/integers/?num=1&min=1&max=10&col=1&base=10&format=plain) via `reqwest` crates. Dump the response in a string. Convert the body into an integer.

This example shows 3 foreign links. I can create a user defined error vie `error_chain` in order to request additional parameters (via the command line) to put into the url.

The main looks like this:

```rust

fn main() {
    if let Err(e) = run() {
        match *e.kind() {
            ErrorKind::Io(ref e) => println!("{:?}", e),
            ErrorKind::Reqwest(ref e) => println!("{:?}", e),
            ErrorKind::ParseIntError(ref e) => println!("{:?}", e),
            ErrorKind::FooError => println!("{:?}", e),
            _ => {}
        }
    }
}
```

Is the idea looks alright and I create a PR for it?

**Comment by budziq** [comment]
Looks good to me :+1:. I'd just try to name the `FooError` to something relevant but sky will not fall on our heads if we don't

**Comment by ludwigpacifici** [comment]
Of course :-)
