### ISSUE TITLE
Cookbook ideas for the env_logger crate

### ISSUE THREAD

**Issue by sebasmagri** [rust-lang-nursery/rust-cookbook#220]
This issue is intended to track recipes for the `env_logger` crate. This would be pretty simple, but please, let me know your ideas!

- [x] [Logging to stdout instead of stderr](https://github.com/brson/rust-cookbook/issues/221)
- [x] [Use a custom environment variable to set up logging](https://github.com/brson/rust-cookbook/issues/222)

**Comment by AndyGauge** [comment]
I can't see the need for additional recipes at this time.  If something new crops up, feel free to open a new issue.
