### ISSUE TITLE
add "read csv records"

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#228]
should show both reading into a StringRecord and typed deserialization with Serde (preferably in two separate short snippets)

cc https://github.com/brson/rust-cookbook/issues/212

See [CONTRIBUTING.md](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by steverob** [comment]
@budziq  I'm working on this :)

**Comment by budziq** [comment]
hi @steverob do you need any help with this?

**Comment by jaroslaw-weber** [comment]
Hey, I noticed that there is already implementation (both reading into an SR and deserialization) in the readme on original csv repository, could we just copy it from there? 
https://github.com/BurntSushi/rust-csv

**Comment by budziq** [comment]
@jaroslaw-weber yeah the csv crate has an excellent cookbook on its own. Most of the examples here were addapted from it  into our coding style. This example does not seam to be in progress, would you be willing to work on it?

**Comment by ludwigpacifici** [comment]
Hello all,

I'll be happy to finish this issue if no one is active. Otherwise, let me know if I can help.

**Comment by budziq** [comment]
@ludwigpacifici go for it :+1:
