### ISSUE TITLE
add "filter csv records matching a predicate"

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#230]
please see [csv tutorial](https://docs.rs/csv/*/csv/tutorial/index.html#pipelining)  if using this resource please remember to attribute original author

cc https://github.com/brson/rust-cookbook/issues/212

See [CONTRIBUTING.md](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by somebrel** [comment]
@budziq I'll work on this one. Can you tag it as _work in progress_ plasse?

**Comment by budziq** [comment]
Hi @somebrel do you need any help with this?

**Comment by somebrel** [comment]
I did it based on the csv tutorial but I am not sure if reading the csv from `stdin` would be the best for a cook-book example... Or is it ok to assume that people are familiar with a `CLI`?

```rust
#[macro_use]
extern crate error_chain;
extern crate csv;

use std::env;
use std::io;

error_chain!{}

fn run() -> Result<()> {
    let query = match env::args().nth(1) {
        None => bail!("expected 1 argument, but got none"),
        Some(query) => query,
    };

    let mut rdr = csv::Reader::from_reader(io::stdin());
    let mut wtr = csv::Writer::from_writer(io::stdout());

    wtr.write_record(rdr.headers().chain_err(|| "cannot read headers")?)
        .chain_err(|| "cannot write headers")?;

    for result in rdr.records() {
        let record = result
            .chain_err(|| "something went wrong reading records")?;
        if record.iter().any(|field| field == &query) {
            wtr.write_record(&record)
                .chain_err(|| "something went wrong writing record")?;
        }
    }

    wtr.flush()
        .chain_err(|| "error ocurr 'flushing' CSV writers buffer")?;
    Ok(())
}

quick_main!(run);
```

**Comment by budziq** [comment]
Hi sorry I took so long to respond. In general It looks nice but I would drop the `chain_err` as these add a little noise (the original example from tutorial was arguably more readable). We would just need to remember to attribute the original author. 

In regard to the cli being used, I wouldn't worry about it but If you think it's clearer, we can replace the query with some hardcoded value.

**Comment by somebrel** [comment]
Alright, thanks! PR coming soon.
