### ISSUE TITLE
setup MacOS CI

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#238]
Our first Windows contributor has stumbled on:

- a [skeptic bug](https://github.com/brson/rust-skeptic/issues/34) 
- non cross platform crate [syslog](https://crates.io/crates/syslog) being used unconditionally

both of these problems would be easily averted if we had more robust CI.

**Comment by anna-liao** [comment]
@budziq Can you elaborate on what you mean by a "more robust CI"?  I could work on the MacOS CI.

**Comment by budziq** [comment]
Hi @anna-liao,

Awesome! 👍
Basically we would like to update our CI to use https://github.com/japaric/trust with Linux and MacOS on travis and windows builds appveyor (basically one has to follow the instructions in trust repo).

there are two additional notes:
- we upload build artifacts (book built with MdBook) to our gh-pages on each successfull commit and merged PR
- we have a cron build on travis with all dependencies set to `"*"` in order to catch buildbreaks with patest crate versions.

If you'd like to work on it or have any questions please do not heasitate to ask here. 😃

**Comment by anna-liao** [comment]
@budziq For the github tokens, do I just use my own when I am testing a fork, and then it will be replaced later when it is merged to rust-lang-nursery/rust-cookbook?  The .yml configuration files require an encrypted version of the github personal access tokens.

**Comment by budziq** [comment]
@anna-liao
yep just use your own tokens for testing on your forks and substitute the travis token with the one already present in our repo when making the PR.

In case of appveyor I am waiting for member of rust-lang-nursery to enable it on canonical account and untill that time we will operate on a fork.

**Comment by alexcrichton** [comment]
@budziq AppVeyor is enabled, see https://github.com/rust-lang-nursery/rust-cookbook/pull/270

**Comment by budziq** [comment]
Thanks @alexcrichton! 
Unfortunately the appveyor is still connected to rust-lang-libs instead of rust-lang-nursery which results in non nursery collaborators such as myself being unable to change settings, start and restart builds (the github rights are not propagated as the appveyor landing url is different than canonical repo address).

At the moment we will work off my personal appveyor account where at least I can admin and grant rights.
Thanks for bootstrapping us and for your time :)

**Comment by budziq** [comment]
Darn. I can't even even switch appveyor instances. So we are stuck with this instance I have no control of.

@alexcrichton Is there a possibility to ad myself as admin for this single repo on appveyor rust-lang-libs without escalating privileges for other projects (like I am in case of travis.ci)?

Being the sole active maintainer without real admin rights is no fun :/

**Comment by alexcrichton** [comment]
I don't know what the rust-lang-nursery org is on AppVeyor, afaik we don't own or have control over that. I also unfortunately don't know how to give out granular permissions in appveyor. If you'd like you can just set it up and do your own thing.

**Comment by budziq** [comment]
Fine grained control can be done by adding separate role and and enabling permissions for that role:
- add a separate role in https://ci.appveyor.com/team under "roles" (something like "Cookbook-Admin") next to "User" and "Admin" with all rights identical to the "User" role (at least Generate API keys)
- change my account role to "Cookbook-Admin"
- add fine grained permissions for "Cookbook-Admin" for specific project under https://ci.appveyor.com/project/rust-lang-libs/rust-cookbook/settings/permissions ("VIEW", "RUN BUILD", "UPDATE SETTINGS")

These should do the trick. But if its problematic I'll live with current setup without admin rights.
Thanks for your time :)

**Comment by alexcrichton** [comment]
Ok I've updated now, try again?

Thanks for the info!

**Comment by budziq** [comment]
Awesome, It works!
Thanks a lot @alexcrichton !

**Comment by budziq** [comment]
@anna-liao there are no more blockers. Are you willing to work on this issue?

**Comment by anna-liao** [comment]
@budziq Thanks!  I tried following the instructions at https://github.com/japaric/trust and tried it out in my fork, but it doesn't seem to be triggering Travis CI and Appveyor.  I won't be able to look into this more until next week, so if someone else would like to set it up, please go for it.

**Comment by budziq** [comment]
@anna-liao 
> it doesn't seem to be triggering Travis CI and Appveyor

Most likely you forgot to go into "settings (gear icon in your fork) > Integrations & services" and enable travis and appveyor integrations. 

> if someone else would like to set it up, please go for it.
There is no rush :) I'll provide minimal appveyor.yml based on Alex's PR so the CI does not constantly error's out until you can approach the issue.

**Comment by budziq** [comment]
Sorry @anna-liao , I needed the MacOS CI up and running before rustfest zurich. I hope that you'll be able to find something interesting to work on on https://gitter.im/rust-impl-period/WG-libs-cookbook!

**Comment by anna-liao** [comment]
no worries, totally understand!
