### ISSUE TITLE
add "Filter a log file by matching multiple regular expressions" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#244]
This example should use [regex](https://crates.io/crates/regex) crate.
It should showoff  [`RegexSet`](https://doc.rust-lang.org/regex/regex/struct.RegexSet.html) usage.

cc https://github.com/brson/rust-cookbook/issues/217

See [CONTRIBUTING.md](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by yandexx** [comment]
Hi! I'll try this one.

I've made a working example so I'll document it properly and make a PR.

I presume this goes into the Basics section.

**Comment by budziq** [comment]
> I presume this goes into the Basics section.

@yandexx  Right. For now we are grouping these into basics and when the section grows too much we will think about good way to split.
