### ISSUE TITLE
Error Chain expansion is easy to overlook.

### ISSUE THREAD

**Issue by isaacg1** [rust-lang-nursery/rust-cookbook#263]
Many of the examples, including `Read lines of strings from a file` and `Read and write integers in little-endian byte order`, have functions called `run()` which return a `Result<()>`. Since `Result` ordinarily has two type parameters, these examples do not immediately compile.

While experienced rust users will be able to handle with something like `use std::io::Result`, a newer user might be at a loss. Since the cookbook will be used heavily by newer users, we should try to make this as easy as possible for them.

I'd be interested in making a Pull Request to handle this, but I'd like to first check that it's a problem that should be solved, and that I'm not missing something.

**Comment by isaacg1** [comment]
I didn't see the error chain information, I apologize. With that in mind, I see that the code doesn't need to be changed. That being said, I do think it's very easy to completely miss the fact that the error handling information is present, since the natural workflow is Table of Contents -> Basics or another specific topic, without ever looking at the About area, and the expand button in the top right is small and subtle. I think it would help if it was more clear that the elements should not be copy-pasted as is, only after expanding. Maybe clicking/highlighting the code should expand the box as well?

**Comment by budziq** [comment]
Hi @isaacg1,

Thanks for great input! I admit that visual and UX side are very lacking at the moment. 

In regard to [copy and pasting](https://github.com/rust-lang-nursery/rust-cookbook/issues/171). A convinient clipboard button  is already implemented upstream and waiting for mdbook release. It will copy all of the contents including the hidden part.

Also I was thinking on making the expand (and other buttons when enabled) more prominent. For instance blink on code mouse over.

We are gathering ideas in [design overhaul issue](https://github.com/rust-lang-nursery/rust-cookbook/issues/246) feel free to add any additional thoughts, suggestions or pain points to that thread.

**Comment by budziq** [comment]
closing as duplicate exists with with some discussion. I'll copy the conversation there.
