### ISSUE TITLE
Add "Run an external command passing it stdin and check for an error code" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#268]
cc #266

See [CONTRIBUTING.md](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by oldmanmike** [comment]
@budziq 

I'd like to start off with this one, if it's okay.

**Comment by budziq** [comment]
Sure @oldmanmike !

**Comment by budziq** [comment]
merged!
