### ISSUE TITLE
Add "Run piped external commands" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#269]
Please propose a nice example of >=2 commands piped to each other.

cc #266

See [CONTRIBUTING.md](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by ludwigpacifici** [comment]
Hello @budziq 

I'd like to give a try at this issue. The example will rely on `std::process::Child` and `std::process::Stdio` in order to run the equivalent  bash command:

```bash
echo "cookbook" | grep -o . | sort | uniq
```

Is it ok with you?

**Comment by budziq** [comment]
@ludwigpacifici excellent! Go for it :+1: 

Although I'd try to use commands that would be both actually useful and not trivially reproduced in pure rust just to make the example more interesting.
If you will have hard time thinking up such example ping me and I'll help.

**Comment by ludwigpacifici** [comment]
Good point ; what do you think about the below?

```bash
# For a given directory, shows the `<number>` biggest files/directories and its human readable size.
du -ah <directory> | sort -hr | head -n <number>
```

`<number>` and `<directory>`can be passed by the command line and use the `clap` crate?

Also, processes can be handle via [`tokio_process`](https://docs.rs/tokio-process/0.2.0/tokio_process/) crate. Should I use it or use the standard one (`std::process`)?

**Comment by budziq** [comment]
Nice! Although I would avoid additional crates here not to obfuscate the examples lets go with just std::process.

**Comment by budziq** [comment]
Hi @ludwigpacifici . Do you need help with this example?

**Comment by ludwigpacifici** [comment]
Thanks @budziq, it should be fine. I send the pull request #297 to start discussing the code review.

**Comment by budziq** [comment]
merged!
