### ISSUE TITLE
Add "scrape information from html" example

### ISSUE THREAD

**Issue by matklad** [rust-lang-nursery/rust-cookbook#277]
Hi!

One common task is to grab some HTML from the web and try to parse some information out of it (a sites doesn't offer JSON API). In Python, I'd use beautiful soup for this, but I am not sure what is the proper tool for Rust.

**Comment by matklad** [comment]
Some amount of googling has lead me to https://github.com/utkarshkukreti/select.rs which seems like a right tool for the job.

**Comment by budziq** [comment]
Hi @matklad 
We have an example using `select` [extract links webpage](https://rust-lang-nursery.github.io/rust-cookbook/net.html#ex-extract-links-webpage).

Which pretty much does what you are suggesting. But if you have any other webscraping usecase I'm game to add another interesting example :smile:

**Comment by matklad** [comment]
My bad, I should have searched better 😅 

See https://github.com/rust-lang-nursery/rust-cookbook/pull/278 :)
