### ISSUE TITLE
How do we keep tables in sync

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#280]
Currently the tables have to be kept in sync:
- intro.md with rest of the chapters
- the chapter tables themselves with the actual examples.

This is error prone and tedious. Most likely the tables should be generated and included into the files. This might be a job for a dedicated function in mdBook or a pre-build script.

**Comment by aturon** [comment]
cc @jaroslaw-weber

**Comment by jaroslaw-weber** [comment]
With custom site generator it is not a problem cause its automatically generated. I have working example in my repo. Reading data from json and generating recipe list.
With mdbook you would need some automation, parsing md files and generating table. But it would be difficult because table is inside the file you would parse so you would  need to edit the file you parse.

**Comment by budziq** [comment]
As discussed on gitter, the categories are quite dynamic, most likely we would need a nightly build to update the tables continuously. In terms of of mdbook, we have markdown inclusion support now, so we could generate/regenerate such markdown containing each table prior to building the book with mdbook (also adding external prebuild script support to mdbook would not be hard or even required).

**Comment by jaroslaw-weber** [comment]
https://github.com/jaroslaw-weber/cookbook_src_generator

I made it working with mdbook.

**Comment by AndyGauge** [comment]
I was toying with the same line of thinking, but ran into an issue with the references.  How does this solution handle links?  Do we need to put all the links in the recipes or do we need to put them in their own file?

**Comment by jaroslaw-weber** [comment]
@AndyGauge 
currently you would need to add links to the end of each md file, but its possible to group those links in one file and append this file to each markdown.

**Comment by AndyGauge** [comment]
I'm doing this and it actually makes creating recipes easier.  I think it is OK to have duplication.

**Comment by AndyGauge** [comment]
In #404 this is addressed by splitting the category files into the series.  The category itself is just the collection of links, and those links are all included in a master TOC.  The only place new recipes are added is the category, and the TOC picks them up automatically.
