### ISSUE TITLE
add "Parse and modify a version string" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#283]
Parse a simple hardcoded version string such as "0.2.6" and increment the major, minor or patch version. Use asserts to verify correct serialization and deserailization.

Use the [semver](https://github.com/steveklabnik/semver) crate

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/276

**Comment by mykalu** [comment]
I'd like to try taking this on!

**Comment by budziq** [comment]
merged
