### ISSUE TITLE
add "Parse a complex version string" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#284]
Parse a complex hardcoded version string such as "1.0.49-125+g72ee7853" (please note "pre" and "build metadata"). Use asserts to verify correct serialization and deserailization.

Use the [semver](https://github.com/steveklabnik/semver) crate

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/276

**Comment by FaultyRAM** [comment]
Working on this one!

**Comment by mykalu** [comment]
When this is approved, I can revise [my code](https://github.com/rust-lang-nursery/rust-cookbook/pull/305) for #283 to make it more consistent with this example's styling.
