### ISSUE TITLE
add "Find the latest version satisfying given range" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#285]
Given a set of version strings, find the latest version in a set that satisfies the given range (like docs.rs does in its urls). Use asserts to verify correct serialization and deserailization.

Use the [semver](https://github.com/steveklabnik/semver) crate

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/276

**Comment by jeramyRR** [comment]
I'd like to take this issue if possible.

**Comment by budziq** [comment]
:+1:

**Comment by budziq** [comment]
Hi @jeramyRR do you need any help to get started here?

**Comment by jeramyRR** [comment]
@budziq, yeah I'm a little stuck.  Semver seems pretty simple, but I'm still a Rust noob.  Can you give me an example of the input?

**Comment by budziq** [comment]
Ok the description might be a little more clear here :)

Basically what I am asking is to take a `Vec` (or an array)  of unparsed version `&str`s, iterate and `map` it to an iterator of `Version`s, filter it against some semver `VersionReq` and pick the latest `Version` (these are sortable so collecting into a `BTreeSet` will do)

To answer your question. Yep rust has both [`HashSet`](https://doc.rust-lang.org/std/collections/struct.HashSet.html) and [`BTreeSet`](https://doc.rust-lang.org/std/collections/struct.BTreeSet.html)

For details on how to match `Version` against `VersionReq` please see the [semver crate docs](https://docs.rs/semver/*/semver/#requirements)

If you have any questions then feel free to ask here :+1: @jeramyRR

**Comment by anna-liao** [comment]
Hi @jeramyRR wondering if you are still working on this issue?
