### ISSUE TITLE
add "Check external command version for compatibility" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#286]
Check if version of external command (i.e. parse output of "$my_binnary --version" external command, or output of some http request to a versioned API)
for compatibility with your application's requirements (i.e. our shellout would work only with given version range of ffmpeg tool). 

Use the [semver](https://github.com/steveklabnik/semver) crate

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/276

**Comment by bobbo** [comment]
Hey, I'm working on this one
