### ISSUE TITLE
add "Create random passwords from a set of allowed characters" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#287]
Given a set of allowed ASCII chars, generate a set of passwords with given length.

Use [rand](https://crates.io/crates/rand) or [ring](https://crates.io/crates/ring) (the ring will most likely be a better idea although the implementation will be more involved) crate

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/227

Thanks for the idea @Phaiax !

**Comment by Pratham567** [comment]
I can assist you in this.

**Comment by devshiva619** [comment]
@budziq can I work on this ?

**Comment by budziq** [comment]
@devshiva619 sure!

**Comment by devshiva619** [comment]
@budziq thats okay :)

**Comment by budziq** [comment]
Hi @Pratham567 do you need any help with this example?

**Comment by anna-liao** [comment]
@Pratham567 Are you still working on this issue?

**Comment by anna-liao** [comment]
@budziq I am interested in working on this issue.  I couldn't find an example for using `ring`.  Here is my first try at writing an example with `rand`, but I am getting an error `error: use of unstable library feature 'ascii_ctype' (see issue #39658)`.

```
extern crate rand;

use std::ascii::AsciiExt;
// alphanumeric and punctuation are allowed, length 30 password
fn main() {
    let mut passwd: Vec<char>;
    let mut index = 0;
    
    while index < 30 {
        let randchar = rand::random::<char>();
        if randchar.is_ascii_alphanumeric() || randchar.is_ascii_punctuation() {
            passwd[index] = randchar;
            index += 1;
        }
    }
    
    println!("{:?}", passwd);
}
```

**Comment by budziq** [comment]
@anna-liao you are trying to use nightly feature 'ascii_ctype' on a stable compiler so it does not work :)

I'd suggest not to over-think the example and just use https://doc.rust-lang.org/rand/rand/trait.Rng.html#method.gen_ascii_chars or if we really want to include the punctuation then we can have minimal reimplementation of it like in https://doc.rust-lang.org/rand/src/rand/lib.rs.html#677.

On a side note, please post a PR even if it is not working, it is easier to discuss then :+1:

**Comment by budziq** [comment]
Thanks! @anna-liao
