### ISSUE TITLE
add "Hash a password with salt" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#288]
Apply the ideas from https://crackstation.net/hashing-security.htm to provide a robust password hashing with salt.

Use [ring](https://crates.io/crates/ring) crate

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/213

**Comment by j-haj** [comment]
I am interested in working on this -- will read through the linked article this weekend

**Comment by j-haj** [comment]
Just to make sure I'm not missing anything, it seems the example should do the following steps:

- Define a password
- Create a salt
- Prepend salt to password
- Create a signing key for HMAC
- Hash password via HMAC

Is there anything missing here you were hoping would be included?

**Comment by budziq** [comment]
@j-haj yep, that pretty much sums it up

**Comment by j-haj** [comment]
@budziq I have a working implementation [1] but after reading #213 I'm not sure what is particularly different from this issue and #289 other than I don't do the verification step. Both are using HMAC, although I suppose #289 doesn't necessarily salt the password (at least it is not explicitly stated in the description). I'm sure I'm missing something, just not sure what that is..

[1] https://github.com/j-haj/password-hash/blob/master/password-hash/src/main.rs

**Comment by budziq** [comment]
@j-haj that is a very nice example indeed! Please post a PR. These two examples might not be that much different. We might eventually decide to merge these into one (but most likely I'll like the #314 to have some more bells and whistles). For now let's go with this one as a basic example and the other PR as something more detailed.

**Comment by Yarn** [comment]
note the small but very important bit of text
"Prepend the salt to the password and hash it with a **standard password hashing** function like Argon2, bcrypt, scrypt, or PBKDF2." (emphasis mine)

HMAC on its own is not a secure password hashing function. Password hashing functions must be secure in the case that the server is compromised (and thus the secret is known). In the case that the secret is known HMAC doesn't provide any security over the underlying hash algorithm.

Fortunately ring implements a suitable password hashing algorithm.
https://briansmith.org/rustdoc/ring/pbkdf2/

The example should probably verify the password against the hash as well as that isn't terribly difficult to mess up.

**Comment by j-haj** [comment]
@Yarn I'm a little confused, from the same page the author states (with regards to HMAC)

> I highly recommend this approach for any large scale (more than 100,000 users) service...

Are you suggesting we first hash via PBKDF2 and then HMAC? The author mentions it's not useful to double hash and in some cases can hurt security. My understanding, which admittedly isn't very deep, is that with PBKDF2 an attacker can still brute-force the hash but it will take longer. On the other hand, the only way the attacked can do the same with HMAC is with the secret key. What am I missing?

**Comment by Yarn** [comment]
The ring implementation of PBKDF2 uses HMAC internally.

That said, I'm fairly sure the quoted text refers to the paragraph directly above it more so than the use of HMAC in general.

I believe the quote you're looking for is
> But, it's better than nothing.

**Comment by j-haj** [comment]
> That said, I'm fairly sure the quoted text refers to the paragraph directly above it more so than the use of HMAC in general.

That is a good observation, I agree

> I believe the quote you're looking for is

>>But, it's better than nothing.

I'm not sure what you mean here... Anyways, clearly you know more about this than I do, and after doing some reading it seems people generally discourage the use of HMAC for storing passwords, so it seems PBKDF2 is the correct approach.

@budziq in light of all this, do you want me to change this to PBKDF2 or proceed with the HMAC implementation?

**Comment by budziq** [comment]
@j-haj admittedly I have not read much of the ring docs. If the informed consensus is to use PBKDF2 then I'm all for it.

**Comment by Yarn** [comment]
> But, it's better than nothing.
It's at the end of the next paragraph about not having specialized hardware or separate servers.

Having read that specific article when I didn't know what I was doing I can confirm you aren't alone in struggling to figure out what you're actually supposed to do.

The first two questions of the FAQ are the part you probably care about. Most of it is nice info but not stuff you should be directly dealing with when writing a web server or such.

**Comment by j-haj** [comment]
@Yarn @budziq I have updated the prior exampe [here](https://github.com/j-haj/password-hash/blob/52a26388a238740580994f34429313b37b72cead/password-hash/src/main.rs#L38) to use PBKDF2. The new example creates a password has and then verifies it. I followed the example from the ring crate, but tried to simplify and shorten it a bit to show the bare minimum functionality.

One thing I am still thinking about is showing the password hash. I print it using lossy utf8, so there are some weird symbols. On the one hand it's nice seeing that it actually worked, on the other hand it is not particularly clean. What are your thoughts?

If this looks good, I'll submit a PR for the cookbook tomorrow.

**Comment by jaemk** [comment]
@j-haj you can hex encode the hash. See the [`hex`](https://crates.io/crates/hex) crate:

```rust
use hex::ToHex;
....
println!("PBKDF2 hash: {:?}", pbkdf2_hash.to_hex());
```

**Comment by Yarn** [comment]
I think you should remove the hmac example. If you put it there that implies that it's an acceptable method for hashing passwords when that isn't really the case. (and my PR for an hmac example just got merged so there is an example covering that now)

for showing it as hex the sha and encode as hex examples use the [data_encoding](https://crates.io/crates/data-encoding) crate, probably want to use that for consistency. I agree that is preferable to representing random bytes as utf8 (which is ambiguous).

**Comment by j-haj** [comment]
As long as there are no objections to using additional crates I think the data encoding crate (for consistency) is a great option.

@Yarn yes I should have been more explicit with my wording -- I left HMAC in, but my intention was to only include the PBKDF2 hash in the actual PR.

Thanks for all the feedback!

**Comment by budziq** [comment]
Thanks a lot for help with this example @Yarn !
