### ISSUE TITLE
add "Check webpage for broken links" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#290]
This is basically an expanded version of [extract links webpage example](https://rust-lang-nursery.github.io/rust-cookbook/net.html#ex-extract-links-webpage)

Use [reqwest](https://crates.io/crates/reqwest) - in conjunction with [select](https://crates.io/crates/select) to check if links on a webpage are not broken (i.e not 404's.)

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/84

**Comment by sb89** [comment]
I'll have a look at this.

**Comment by budziq** [comment]
:+1:

**Comment by budziq** [comment]
merged
