### ISSUE TITLE
add "Make a partial download with HTTP range headers" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#291]
Use [reqwest](https://crates.io/crates/reqwest) - in conjunction with HTTP range headers to make a partial download of a large file with progress.

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/84

**Comment by sofiageo** [comment]
Seems like @jbolila beat me to it :) I didn't make any request comment because i didn't know how far I could go, but if was my first try with rust. 

I will still post my code for any comments 
```
#[macro_use]
extern crate error_chain;
extern crate reqwest;

use std::io::Read;
use reqwest::header::{Headers, Range};

error_chain! {
    foreign_links {
        Io(std::io::Error);
        HttpRequest(reqwest::Error);
        ParseRequest(reqwest::UrlError);
    }
}

fn run() -> Result<()> {
    let url = reqwest::Url::parse("https://rust-lang-nursery.github.io/rust-cookbook/")?;
    let client = reqwest::Client::new()?;

    print!("Making a HEAD request: ");
    let mut req = reqwest::Request::new(reqwest::Method::Head, url.clone());
    let mut res = client.execute(req)?;
    println!("done!");
    let headers= res.headers();
    let supported = headers.get_raw("Accept-Ranges");
    if supported.is_some() {
            let mut headers = Headers::new();
            headers.set(Range::bytes(1, 100));

            println!("Making a GET request: ");
            let mut res = client.get(url.clone())?.headers(headers).send()?;
            let mut body = String::new();
            res.read_to_string(&mut body)?;

            println!("Status: {}", res.status());
            println!("Headers:\n{}", res.headers());
            println!("Body:\n{}", body);
    }

    Ok(())
}

quick_main!(run);
```

**Comment by budziq** [comment]
@sofiageo no reason to shy away from claiming an issue, we are not pressed for any deadline here! Just pick another issue and start working on it.

In regard to how this issue should be done, please checkout @jbolila 's PR once it's ready (I'll probably do a review there tomorrow). Your code is quite nice but with few suggestions:
- use convenience method https://docs.rs/reqwest/0.8.0/reqwest/struct.Client.html#method.head instead of `reqwest::Request::new(reqwest::Method::Head`
- use typed api `headers.get` instead of `headers.get_raw`
- no need to create temporary `mut headers` variable it can be constructed within the `?.headers(..).send` call
- we might prefer to read bytes instead of into string (strings must be utf8 and typical binary data would not)
- we would like to read the supported range from the header to request an appropriate range

**Comment by budziq** [comment]
Merged!

**Comment by ollyde** [comment]
@budziq I don't see any docs for this on the link

Trying with

    // Make a GET request to fetch the first 512 bytes of the file
    // Replace with the actual URL
    let resp = client
        .get(public_link)
        .header(reqwest::header::RANGE, "bytes=0-511")
        .send()
        .await
        .map_err(|e| {
            eprintln!("Error fetching file: {}", e);
            ApiError {
                status: "issue-fetching-file".to_string(),
                message: "Error fetching file for get_mime_from_url".to_string(),
            }
        })?
        .bytes()
        .await
        .map_err(|e| {
            eprintln!("Error fetching bytes file: {}", e);
            ApiError {
                status: "issue-fetching-file".to_string(),
                message: "Error fetching bytes for get_mime_from_url".to_string(),
            }
        })?;

But I get length 0.
