### ISSUE TITLE
add "Compile and link statically to a bundled C library" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#292]
Use [cc-rs](https://crates.io/crates/cc-rs) crate to compile and link statically to a bundled C library inside of a build.rs file.

Please note that it will be important to mention that this is a **build time** crate.
Most likely we will dedicate a separate (last) chapter like "build_time.md"

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/236

**Comment by jaemk** [comment]
Note: The [`trust`](https://github.com/japaric/trust) repo is itself a basic example that could be copied and simplified.

**Comment by budziq** [comment]
Right! @jaemk Would you be interested in taking lead on this example?

I see this as the first example that would have the longest explanation followed by the next 4 examples listed in https://github.com/rust-lang-nursery/rust-cookbook/issues/236 showing the possible minor differences (with much shorter descriptions)

**Comment by jaemk** [comment]
Sure! I can take a look at this tomorrow and setup a new `build_tools` file

**Comment by budziq** [comment]
merged
