### ISSUE TITLE
add "Compile a C library while setting custom defines" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#295]
Use [cc](https://crates.io/crates/cc) crate to compile a C library from a build.rs file while setting custom defines/CFLAGS.

Please note that it will be important to mention that this is a **build time** crate.
Most likely we will dedicate a separate (last) chapter like "build_time.md"

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/236

**Comment by bobbo** [comment]
I can take a look at this one
