### ISSUE TITLE
add "Compile and link statically to a bundled C++ library" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#296]
Use [cc](https://crates.io/crates/cc) crate to compile and link statically to a bundled C++ library inside of a build.rs file.

Please note that it will be important to mention that this is a **build time** crate.
Most likely we will dedicate a separate (last) chapter like "build_time.md"

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/236

**Comment by j-haj** [comment]
That link is broken for me - did the crate change it's name to cc? It seems to refer to itself both as cc and cc-rs. I'm assuming [this](https://crates.io/crates/cc) is the crate you are referring to

**Comment by budziq** [comment]
@j-haj darn they renamed again. I've updated te link. Thanks!

**Comment by thibaultbarbie** [comment]
I would like to take it if it is ok ?

**Comment by hackertron** [comment]
Is this issue still open for contributor ?

**Comment by budziq** [comment]
@hackertron unfortunately it already has a PR awaiting review (please note the "wip / claimed" label) but you ar welcome to chose any nonclaimed example or propose a new one!

**Comment by budziq** [comment]
merged!
