### ISSUE TITLE
Cookbook ideas for num_cpus

### ISSUE THREAD

**Issue by bobbo** [rust-lang-nursery/rust-cookbook#300]
Come up with ideas for nice introductory examples of using the num_cpus crate, possibly in combination with other crates, that would be good to show in the Rust Cookbook. Please leave a comment here with your ideas! You don't necessarily have to write the example code yourself but PRs are always welcome!

EDIT:
- [x] [Draw a fractal using a threadpool](https://rust-lang-nursery.github.io/rust-cookbook/concurrency.html#ex-threadpool-fractal) - uses num_cpus - and basically all the other threadpool examples that are going to be implemented
- [x] [Check number of logical cpu cores](https://github.com/rust-lang-nursery/rust-cookbook/issues/301)

**Comment by budziq** [comment]
@bobbo I've added a single example idea for now.
Another is to "Get number of physical cpu cores" unfortunately I do not like that the [`get_physical`](https://docs.rs/num_cpus/1.7.0/num_cpus/fn.get_physical.html) falls back to logical cores if physical cant be queried making such example unreliable (I'would suggest for this function to return a `Result`) I'll propose it on blitz evaluation thread.

**Comment by AndyGauge** [comment]
This tracking issue seems resolved.
