### ISSUE TITLE
add "Check number of logical cpu cores" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#301]
Use [num_cpus](https://crates.io/crates/num_cpus) check number of logical cpu cores.

cc https://github.com/rust-lang-nursery/rust-cookbook/issues/300

**Comment by V1shvesh** [comment]
@budziq I wish to work upon this. Can I get some more info?

**Comment by budziq** [comment]
@V1shvesh Sure! Please provide an example using [`num_cpus::get`](https://docs.rs/num_cpus/1.7.0/num_cpus/fn.get.html) function to get and printout number of logical cpus in the system. This would be basically a one-liner plus boilerplate. Please checkout the already existing examples in basics section.

**Comment by V1shvesh** [comment]
Thanks for the info!

**Comment by V1shvesh** [comment]
@budziq I've written the code now. Can you tell  me where should I add this?

**Comment by budziq** [comment]
@V1shvesh I would go with the basics section

**Comment by V1shvesh** [comment]
So, I gotta update the basics.md. Got it. But what should I write under the crates and categories column?

**Comment by budziq** [comment]
under crates you would add a linked "num_cpus" badge similar to other examples. An under the categories we add the linked category sections from crates.io entry for given crate (unless the crate has none then we try to match some but luckily num_cpus has a category listed)
