### ISSUE TITLE
Add "Test if all/any items match predicate in parallel" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#331]
Showcase a [`any`](https://docs.rs/rayon/*/rayon/iter/trait.ParallelIterator.html#method.any) and [`all`](https://docs.rs/rayon/*/rayon/iter/trait.ParallelIterator.html#method.all) with [rayon](https://crates.io/crates/rayon) crate.

Please discuss the idea here before starting implementation.
cc https://github.com/rust-lang-nursery/rust-cookbook/issues/272

**Comment by CJStadler** [comment]
I'm interested in working on this. Should this be one or two examples? Do we want something more complicated than "check whether all the elements in this array are even"? These functions are so basic that it feels like adding additional complexity might just obscure their use without adding value.

**Comment by budziq** [comment]
I would go with the simplest approach possible (also mentioning the sequential versions from std in the description). We can showcase both `all` and `any` in the same snippet.
