### ISSUE TITLE
modernize examples for rust 1.21 (`Iterator::for_each`)

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#332]
Our examples have a lot of for loops that operate on chained iterators just to consume the values for their side effects (typically a single `println!`).

As the [`Iterator::for_each`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.for_each) has been stabilized in rust 1.21 we can make the examples a little more idiomatic. Lets use `for_each` instead of for loop when we have chained iterator calls.

**Comment by sb89** [comment]
I can have a look at this.
