### ISSUE TITLE
Add "Process child process output continuously" example

### ISSUE THREAD

**Issue by abitrolly** [rust-lang-nursery/rust-cookbook#339]
Please provide an example using std only that shows how to process child process output (stdout) continuously without waiting for the child to finish.

cc #266 

Original request below:

--------

In https://rust-lang-nursery.github.io/rust-cookbook/basics.html#ex-parse-subprocess-output it looks like the example waits for subprocess to finish before processing output. How to process program output in realtime similar to what `grep` does?

Also, if the reading operation is blocking and child process hangs without any output, how to implement a timeout in this situation?

**Comment by budziq** [comment]
Thanks @abitrolly !

The key ingredients here are to use `Command::new("long_running_process").stdout(Stdio::piped())`
and passing the `child.stdout` into the `BufReader::new`. 
This should be quite straightforward, would you like to submit a PR for it? I'll help you along the way :)

**Comment by ludwigpacifici** [comment]
One example idea for this one:

Spawn the `ping localhost` process and display live statistics like the average/minimum/maximum round trip.

If you are happy with this guys, I can give it a go.

**Comment by budziq** [comment]
@ludwigpacifici I'd actually suggest something a little simpler like filtering `dmesg` or `journalctl` in the realtime.

**Comment by abitrolly** [comment]
I am interested, but not sure if I could get back to this soon. I didn't stress it much, but for me the key point was not to block main thread while program is waiting for input, so that if there is no input for some time, the program could report it.

**Comment by budziq** [comment]
I'm personally game with anyone taking this example.

About implementing some kind of a timeout, this would require threading and I'm not sure if it would be a perfect cookbook example but i might be convinced otherwise. Anyhow I'd prefer for this example to be minimal as described (without timeout) and we might see if we can provide a second more involved version with timeout.

**Comment by ludwigpacifici** [comment]
@abitrolly I let you decide if you want to go for it :-)

Slightly off topic: 
> About implementing some kind of a timeout, this would require threading and I'm not sure if it would be a perfect cookbook example but i might be convinced otherwise

Could it be an example to show async recipe with the tokio crate? And more generally, is there a plan to have a section about tokio?

**Comment by budziq** [comment]
> Could it be an example to show async recipe with the tokio crate?

Sure :)

>  is there a plan to have a section about tokio?

Yep [there is](https://github.com/rust-lang-nursery/rust-cookbook/issues/267). Unfortunately the async story for rust is not stable yet (and will not be for some time), so we will wait with such examples until async in the language and ecosystem matures a little.

**Comment by ludwigpacifici** [comment]
> @abitrolly I let you decide if you want to go for it :-)

Hey @abitrolly, are you still interested?

**Comment by abitrolly** [comment]
@ludwigpacifici unfortunately, there still no time for Rust, and I don't expect things to change any time soon.

**Comment by budziq** [comment]
ok so the issue is up for grabs again

**Comment by ludwigpacifici** [comment]
In that case, I can have a look?

**Comment by budziq** [comment]
sure!
