### ISSUE TITLE
Add "Redirect both stdout and stderr of child process to the same file" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#345]
see https://users.rust-lang.org/t/double-redirection-stdout-stderr/13554

cc #266

**Comment by ludwigpacifici** [comment]
I will have plenty of free time in the airport today (and no good idea yet for #215), so I don't mind to write a recipe :-)

I was thinking to use the command `find / -name rust` to write outputs and errors into the same file. Is this command suitable?

**Comment by budziq** [comment]
@ludwigpacifici 
Lets just write the recipe and worry about the exact command later on (it's just an implementation detail).
For now we can assume that "find /" is ok :)
