### ISSUE TITLE
add "Transform csv columns" example

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#346]
please see [csv cookbook](https://docs.rs/csv/*/csv/cookbook/index.html) if using this resource please remember to attribute original author

example should show how to transform csv columns (ie. split one column into many https://github.com/rust-lang-nursery/rust-cookbook/issues/212#issuecomment-336325467)

cc #212

See [CONTRIBUTING.md](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by AndyGauge** [comment]
See #348
