### ISSUE TITLE
Add "use of functions from the Datelike and Timelike traits such as month, weekday, hour, minute" example

### ISSUE THREAD

**Issue by ludwigpacifici** [rust-lang-nursery/rust-cookbook#357]
With the [`chrono`](https://crates.io/crates/chrono) crate, write a recipe showing the use of [`chrono::Datelike`](https://docs.rs/chrono/*/chrono/trait.Datelike.html) and [`chrono::Timelike`](https://docs.rs/chrono/*/chrono/trait.Timelike.html) traits.

cc #324

See [CONTRIBUTING.md](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by CrockAgile** [comment]
I'll volunteer to add this example
