### ISSUE TITLE
Add "Converting a local time to UTC time and and vice versa" recipe

### ISSUE THREAD

**Issue by ludwigpacifici** [rust-lang-nursery/rust-cookbook#360]
With the [`chrono`](https://crates.io/crates/chrono) crate and for a given timezone, write a recipe converting a local time to UTC time and converting a UTC time to local time.

cc #324

See [CONTRIBUTING.md](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/CONTRIBUTING.md) and [Pull request template](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/.github/PULL_REQUEST_TEMPLATE.md) for details.

**Comment by Lapz** [comment]
I'll claim this one
