### ISSUE TITLE
Add "Converting a formatted date to a Unix timestamp and vice versa" recipe

### ISSUE THREAD

**Issue by ludwigpacifici** [rust-lang-nursery/rust-cookbook#361]
With the [`chrono`](https://crates.io/crates/chrono) crate, write a recipe converting a formatted date (for example `YYYY-MM-DD:HH:MM:SS`) to a Unix timestamp. Convert it also the other way around.

cc #324

See [CONTRIBUTING.md](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/CONTRIBUTING.md) and [Pull request template](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/.github/PULL_REQUEST_TEMPLATE.md) for details.

**Comment by pduzinki** [comment]
I'd like take this one.
