### ISSUE TITLE
Add "Send a struct through a TCP connection"

### ISSUE THREAD

**Issue by gbip** [rust-lang-nursery/rust-cookbook#363]
With [serde](https://serde.rs/) and `std` create a client that sends a struct to a server.

**Comment by budziq** [comment]
Hi @gbip thanks. Please submit the example idea as a comment to one of the issues marked "tracking issue" where we can discuss them as described in [contributing.md](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/CONTRIBUTING.md#finding-what-to-contribute). We tend to create separate implementation issues only once the idea was accepted. I'll close this one for now untill we can flesh out the required details in the tracking issue 👍

**Comment by budziq** [comment]
I'd submit it to [misc ideas](https://github.com/rust-lang-nursery/rust-cookbook/issues/24) section untill we get a proper wishlist for the community to edit.
