### ISSUE TITLE
Update the logging section to log 0.4, log4rs 0.8 env_logger 0.5

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#383]
Log and env_logger have released a major API overhaul with 0.4 (log) and 0.5.0-rc.2 (env_loger) which has impacted the whole logging.md section.

Lets update the Cargo.toml and the logging.md examples to pass `cargo test` bonus points for making the examples more idiomatic in regard to newest API :smile:

**Comment by gaurikholkar** [comment]
Would like to work on this :)

**Comment by gaurikholkar** [comment]
@budziq I am having a small issue understanding how the `foreign_links` will change now, the syntax part.

**Comment by budziq** [comment]
Thanks for taking a look :) :+1: 

Hmm this looks like a problem with error-chain or how it interacts with new log 0.4 and old env_logger 0.4. Would you be willing to submit the problem to `log`  and `error-chain` repos? As far as I know the new log facade in 0.5 should be backwards compatible.

Anyhow we should also switch to `env_logger = "0.5.0-rc.2"` which has infailable inits. This should mitigate the problem. Lets see how far we can go.

Please remember to remove error-chain and switch `run` to normal `main` if error-chain usage is unnecessary in the example.

**Comment by gaurikholkar** [comment]
@budziq yeah will open up issues in the respective repositories :) and cc you

**Comment by budziq** [comment]
fixed with https://github.com/rust-lang-nursery/rust-cookbook/pull/412
