### ISSUE TITLE
Concurrency vs parallelism?

### ISSUE THREAD

**Issue by shmerl** [rust-lang-nursery/rust-cookbook#384]
The chapter on concurrency uses it interchangeably with parallelism which makes it somewhat confusing. Concurrency usually focuses on splitting some task into chunks of execution, that can progress concurrently (but not necessarily purely in parallel). I.e. you can have one thread performing concurrent tasks and interrupting / jumping between them (like with coroutines). Parallelism on the other hand means real parallel execution (threads) when those tasks progress literally at the same time. Some scenarios can combine both parallelism and concurrency together.

May be these two concepts should be more clearly delineated and examples should cover both.

**Comment by budziq** [comment]
Hi @shmerl. If you have clear idea on how to improve the chapter I'm up for discussion or PR's ;)

**Comment by AndyGauge** [comment]
I'm not a computer science major, so I often make mistakes when I try to correct terms.  I have broken the chapter into 2 series with #404 You can see the parallel tasks series within the concurrency chapter here: http://www.yetanother.site/rust-cookbook/concurrency.html  Let me know if there's improvements to be made.

**Comment by AndyGauge** [comment]
If you would like to reopen this issue, feel free, but there have been significant changes to to wording in #404
