### ISSUE TITLE
example's date pattern is not "hyphenated British English", it's ISO 8601

### ISSUE THREAD

**Issue by skierpage** [rust-lang-nursery/rust-cookbook#386]
The Basics example **Replace all occurrences of one text pattern with another pattern** says it
> Replaces all occurrences of the hyphenated British English date pattern  `2013-01-15`

But this doesn't match any British date format, whose key feature is the day of the month comes first, i.e. `15-1-2013` (cf. https://www.englishclub.com/vocabulary/time-date.htm).  The dates in the example are simply (and wonderfully) in the standard ISO 8601 date format, so change ENGL_DATE_REGEX to ISO8601_DATE_REGEX, etc.

Oblig. xkcd: https://xkcd.com/1179/ 😃
BTW the cookbook is amazing, the |> play button in the browser is magic!

**Comment by budziq** [comment]
Hi @skierpage sory for late reply and thanks :D

But you have not actually made this change into a PR against this repo.  Please submit the PR and I'll gladly merge it!

**Comment by budziq** [comment]
Oh it's already merged in another PR ;)
