### ISSUE TITLE
Compile and link statically do a bundled C++ library does not compile

### ISSUE THREAD

**Issue by Fierthraix** [rust-lang-nursery/rust-cookbook#388]
[This example](https://rust-lang-nursery.github.io/rust-cookbook/build_tools.html#ex-cc-static-bundled-cpp) doesn't compile currently.

The function inputs in [`foo.cpp`](https://rust-lang-nursery.github.io/rust-cookbook/build_tools.html#srcfoocpp) aren't specified, and the return type needs to be added to the `extern` in [`main.rs`](https://rust-lang-nursery.github.io/rust-cookbook/build_tools.html#srcmainrs-1).

Right now the cpp code an error saying `x` and `y` were not declared.
```
cargo:warning=src/foo.cpp: In function ‘int multiply()’:
cargo:warning=src/foo.cpp:7:12: error: ‘x’ was not declared in this scope
cargo:warning=     return x * y;
cargo:warning=            ^
cargo:warning=src/foo.cpp:7:16: error: ‘y’ was not declared in this scope
cargo:warning=     return x * y;
cargo:warning=                ^
exit code: 1
```
The rust side fails with
```
error[E0277]: the trait bound `(): std::fmt::Display` is not satisfied
 --> src/main.rs:7:24
  |
7 |         println!("{}", multiply(5, 7));
  |                        ^^^^^^^^^^^^^^ `()` cannot be formatted with the default formatter; try using `:?` instead if you are using a format string
  |
  = help: the trait `std::fmt::Display` is not implemented for `()`
  = note: required by `std::fmt::Display::fmt`
```
as the return type is currently `()`

**Comment by budziq** [comment]
Fixed with https://github.com/rust-lang-nursery/rust-cookbook/pull/385
