### ISSUE TITLE
Make HTTP request and parse mime type

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#397]
In this example, make a request to a static url and parse the mime type response.  Potentially show 2 mime types and an request without a mime header.

**Comment by NiekGr** [comment]
Dear Maintainers,

I just started learning Rust and read through chapters 1 to 15 of the Rust book. And I would like to create an example for the cookbook.

Can I take on this issue?

Best Regards,

NiekGr

**Comment by AndyGauge** [comment]
Absolutely 👍

**Comment by NiekGr** [comment]
Thank you!

**Comment by NiekGr** [comment]
@AndyGauge could you explain what you mean with "show 2 mime types and a request without a mime header"? Would a message if there isn't a mime type found and two or three messages if there is a mime type found, be good enough?

Or would you also like to see the function being called three times with the output?

**Comment by NiekGr** [comment]
Oké, that is just what I did. I will add the boilerplate and documentation.

**Comment by brandonros** [comment]
I think it'd be a huge help to show how to fire off 2 HTTP requests at once. I feel like that would introduce a much more "real word"-like workload.

It's going to introduce Futures, tokio, an executor, and all of that stuff? Right?
