### ISSUE TITLE
Recipe for Mime::FromStrError

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#398]
Show an invalid mime string, and how to handle processing the error.

**Comment by math-foo** [comment]
Hi! I'd like to write an example for this one; but I am not sure what you are looking for in terms of handling the error. Calling `parse` on a string returns a `Result<Mime, FromStrError>`. Error handling beyond that would depend a lot on the nature of the function. Is there something that you're looking for beyond returning a `Result` with `?`?

**Comment by AndyGauge** [comment]
Well, I was hoping to see parsing a string, having the error happen, and fall back to a default action.  I've seen a default value of application/octet-stream be set when no other type is reasonable.
