### ISSUE TITLE
file names that have been modified in the last 24 hours for the working directory

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#399]
Find the file names in a directory modified in the last 24 hours. (Uses `std`).

**Comment by ludwigpacifici** [comment]
Is the archive bit Windows specific? As for Linux, is this example not redundant with the `std` [documentation](https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.modified)?

To make this recipe more interesting, why not write a basic implementation of `ls` (Linux) or `dir` (Windows)?

```
$ ls -l foo.txt

| File Permissions | Owner | Group | Size | Modified Time  | Name    |  
|------------------+-------+-------+------+---------------+---------+
| -rw-r--r-- 1     | lud   | lud   |    6 | Apr 24 20:31  | foo.txt |
```

I was also thinking about inode number, but it's Linux specific.

**Comment by AndyGauge** [comment]
Yes that would be a good start to it.  I was thinking get file names that have been modified in <24 hours for the working directory.  That takes the `std` example and builds on it.

**Comment by ludwigpacifici** [comment]
Fair enough. Can I give a go at "file names that have been modified in <24 hours for the working directory"?

**Comment by AndyGauge** [comment]
That would be awesome.
