### ISSUE TITLE
FontAwesome missing since mdBook 0.1.7

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#416]
Since switching to latest mdBook the FontAwesome fonts are missing from the gh-pages
it has been fixed in https://github.com/rust-lang-nursery/mdBook/pull/697 but untill it is released to crates.io we need a workaround...

**Comment by budziq** [comment]
Hotfix was commited in https://github.com/rust-lang-nursery/rust-cookbook/commit/331171bfbbee7dc333a41ed49db1edb916df2267

I'd preffer to leave this issue open untill new mdBook is relased with propper fix so we remember to cleanup deploy.sh.

**Comment by AndyGauge** [comment]
0.1.8 released today, this change should be included.  I'll test out mdbook 0.1.8 with a PR to remove the hotfix.

**Comment by budziq** [comment]
Unfortunately the rust-cookbook published at https://rust-lang-nursery.github.io/rust-cookbook/ started  missing the font awesome icons. 
![font_fail](https://user-images.githubusercontent.com/221000/42534740-c3bfb2b4-848d-11e8-9f96-805c5066218e.png)

So I guess that the 0.1.8 does not fix this issue...

**Comment by AndyGauge** [comment]
I think the problem is my failure to update the template.

Thanks for catching that, I didn't wait long enough for it to update yesterday.

**Comment by budziq** [comment]
Thanks for taking care of this @AndyGauge !

**Comment by AndyGauge** [comment]
:tada:
