### ISSUE TITLE
cargo test warns with lint unused_doc_comment has been renamed

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#423]
warning: lint unused_doc_comment has been renamed to unused_doc_comments
```
  --> /tmp/rust-skeptic.Aq6OdV6EK5TS/test.rs:13:1
   |
13 | / error_chain! {
14 | |    foreign_links {
15 | |        CsvError(csv::Error);
16 | |        ParseInt(std::num::ParseIntError);
...  |
20 | |    }
21 | | }
   | |_^
   |
```
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more i

**Comment by budziq** [comment]
Moving to `error_chain = 0.12.0` should silence this error https://github.com/rust-lang-nursery/error-chain/issues/245
