### ISSUE TITLE
Replace quick_main with main returning Result

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#433]
Rust 1.26 allows return types on main.  This should be taught in the cookbook, rather than relying on quick_main.  

TODO: 

- [ ] Replace functions in recipes that leverage a function returning a Result and quick-main macros
- [ ] Document in a note about error handling

https://www.reddit.com/r/rust/comments/8xubdr/rust_cookbook_is_now_reorganized/e28efj7/

**Comment by sepiropht** [comment]
I will Be happy to take this one too

**Comment by budziq** [comment]
+1

**Comment by budziq** [comment]
Yep, optimaly all occurences should be unneccessary now including the non example text sections. Just grep the source for `quick_main`. If you'll have any questions just drop a comment here.

**Comment by AndyGauge** [comment]
cc #525
