### ISSUE TITLE
Recipe Series: Sort Vector

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#437]
|  |  |
| ------------- | ------------- |
| Crates  | std  |
| Section  | 1.1 Sorting  |

This recipe series should demonstrate how sorting a vector is accomplished.  The initial recipe is a simple `std` implementation of sorting integers, and descending.  Next show how to sort `f64`. Implement a custom struct and demonstrate sorting a vector of these types.

**Comment by Januson** [comment]
Hello. May I work on this issue?

**Comment by budziq** [comment]
Sure @Januson !
