### ISSUE TITLE
Recipe: Download GZip content

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#439]
|  |  |
| ------------- | ------------- |
| Crates  | reqwest, flate2  |
| Section  | 3.2 Download GZip content  |

Download and decompress gzipped content from an Http site.

**Comment by sepiropht** [comment]
Can i take this ?

**Comment by budziq** [comment]
sure!

**Comment by AndyGauge** [comment]
Turns out reqwest does this natively, by default.  Literally nothing to show.  Bad example.
