### ISSUE TITLE
Recipe: Trigonometry

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#445]
|  |  |
| ------------- | ------------- |
| Crates  | std |
| Section  | 16.1 Mathematics  |

Create a recipe that demonstrates using `f64` solving simple triangle problems with `sin`, `cos`, and `tan`.

**Comment by AndyGauge** [comment]
I'm hoping to make a series, where this provides a simple usage, and #452 expounds on it.

**Comment by JamesHinshelwood** [comment]
So, I'm thinking of just a couple of samples. One where we calculate the angle of a triangle with side lengths X and Y. Then maybe another sample where we verify sin X/cos X = tan X for some specific value of X.
@AndyGauge How does this sound?

**Comment by AndyGauge** [comment]
Two distinct samples would be good.  I'm really looking for something that anyone taking high school level math could reason.  Those examples are definitely reasonable.  You also have some wiggle room in there if you hit a roadblock with that specifically.
