### ISSUE TITLE
Recipe: Distance between points

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#446]
|  |  |
| ------------- | ------------- |
| Crates  | std, num |
| Section  | 16.1 Mathematics  |

Given a geo-coordinate pair (lat/long) of 2 points, find the distance between them.

**Comment by ludwigpacifici** [comment]
Hello @AndyGauge 

I'd be happy to write that recipe.

**Comment by Munchotaur** [comment]
There is a minor error in this recipe. Paris is to the east of the prime meridian, so its coordinates should be assigned with a positive longitude, not negative:
 
`    let (paris_latitude_degrees, paris_longitude_degrees) = (48.85341_f64, 2.34880_f64);`
