### ISSUE TITLE
Recipe: Complex Numbers

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#448]
|  |  |
| ------------- | ------------- |
| Crates  | num |
| Section  | 16.1 Mathematics  |

Demonstrate using complex numbers (n+m√-1) with num crate

**Comment by GuineaPiet** [comment]
Going to give this a shot

**Comment by GuineaPiet** [comment]
Let me know if more things are needed and I'll adjust the PR accordingly 😃
