### ISSUE TITLE
Recipe: Matricies Series

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#450]
|  |  |
| ------------- | ------------- |
| Crates  | ndarray |
| Section  | 16.2 Matricies  |

Investigate and create the following recipes:

- [x] Add two vectors
- [x] Norm of two vectors
- [ ] A vector time a matrix
- [ ] Add, multiply two matrix
- [x] invert a Matrix
- [x] A scalar time a vector time a matrix
- [ ] Serialize/Deserialize a big matrix

**Comment by j-haj** [comment]
Section 16 is Text Processing - is the intent for `ndarray` work to land in the text processing section?

**Comment by AndyGauge** [comment]
Section 16 is Science.  It doesn't exist yet.  I think #452 Creates the Science section.

**Comment by mfajer** [comment]
I'll work on this one.

**Comment by AndyGauge** [comment]
@mfajer do you want all of them or just a few?  Feel free to do individual PRs per recipe.

**Comment by j-haj** [comment]
@mfajer FYI I have started working on the vector sum item

**Comment by j-haj** [comment]
Per #452, I think this work belongs under `linear-algebra`, so the directory layout will be `src/science/mathematics/linear-algebra/`.

**Comment by mfajer** [comment]
@AndyGauge I will do individual PRs per recipe so that @j-haj and others can contribute.

**Comment by JamesHinshelwood** [comment]
@j-haj @mfajer I would like to help out with some of these recipes, if they aren't already being worked on. Which are in progress? Would I be safe to start with some of the matrix stuff?

**Comment by j-haj** [comment]
@JamesHinshelwood yea! I have a PR for the vector sum example and will have another PR for the vector norm example shortly, so those two are good. I'm not sure what @mfajer is working on but as far as I am aware everything else is up for grabs.

**Comment by JamesHinshelwood** [comment]
`ndarray` does not provide a method to calculate the inverse of a matrix. This is provided by the [`ndarray_linalg`](https://docs.rs/ndarray-linalg/0.10.0/ndarray_linalg/index.html) crate - should we use this?

Or perhaps we could use `nalgebra`? (which I have a personal preference for :wink:)

**Comment by j-haj** [comment]
@JamesHinshelwood on the one hand the current examples use `ndarray`, so maybe `ndarray_linalg` would be more familiar. On the other, `nalgebra` seems more complete and is probably would I would choose if I were going to do any kind of linear algebra. My vote is for `nalgebra` due to its completeness and has the advantage of exposing readers to multiple options.

**Comment by mfajer** [comment]
Sorry, got caught up with work and couldn't comment until now.  I had done a few iterations of the vector norm example but @j-haj beat me to it so I just commented on his PR to give some thoughts.  I would also vote for algebra, it seems less generic by sticking to vectors and matrices but in a much nicer framework than ndarray-linalg for example.

**Comment by mfajer** [comment]
@AndyGauge looking through those discussion it appears you want to use ndarray in the Science section and not algebra, is that correct?  I'll rework by scalar * matrix * vector example then.

**Comment by mfajer** [comment]
Nevermind, I just read through #471 and it looks like the only outstanding examples are the matrix inversion and sterilization/deserialization.

**Comment by AndyGauge** [comment]
I hear a vote for nalgebra in Science, It is plausible that we will end up there.

**Comment by KappaDistributive** [comment]
In #508, motivated by Andy Gauge's endorsement of nalgebra, I proposed an example of matrix inversion.

I'd like to point out that this opens the door to many fundamental tasks in linear algebra. Examples: 

- calculating the determinant of a given square matrix,

- calculating the included angle between two vectors,

- calculating the area of the parallelogram spanned by two vectors,

- determining (unique) solutions to a given linear equation,

- finding the closest point on a line to a given point,

- ...

Being a mathematician by trait, I'm not sure which of these would be interesting to the community. But I'd personally like to see an extended list of examples in linear algebra to be implemented.

**Comment by mxxo** [comment]
Building on KappaDistributive's work with `nalgebra`, I made an example for finding matrix eigenvalues using the `nalgebra-lapack` helper crate (#553).

**Comment by KappaDistributive** [comment]
@AndyGauge invert a matrix is present in `science/mathematics/linear_algebra` and hence should get a tick in your todo list.
