### ISSUE TITLE
Recipe: Creating Tables in Database

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#454]
|  |  |
| ------------- | ------------- |
| Crates  | rusqlite|
| Section  | 7.1 SQLite  |

Build off of creating a database by creating a database structure

**Comment by lnicola** [comment]
Claimed by myself as discussed in #453.

**Comment by lnicola** [comment]
This was closed by mistake, can you please reopen it?

**Comment by AndyGauge** [comment]
I'm available to help if you need anything

**Comment by lnicola** [comment]
It was implemented in #464, right?

**Comment by AndyGauge** [comment]
I didn't read the recipe, I just read the title, but it looks like it was.  I'll close this and update the Recipe Title.

Thanks!
