### ISSUE TITLE
Recipe Series: Postgres

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#456]
|  |  |
| ------------- | ------------- |
| Crates  | postgres |
| Section  | 7.2 Postgres Database  |

Looking for 3 Recipes that demonstrate using Postgres to:

 - [x] Create Tables and database structure
 - [x] Perform Simple insert and query operation
 - [x] Perform aggregate operations

The goal of the cookbook is to provide enough insight about the crates that anyone could get their feet wet, and learn the best practices.

**Comment by AndyGauge** [comment]
There should be a new section 'Database' that comes after data structure.  SQLlite comes first then Postgres.

**Comment by AndyGauge** [comment]
Do you want the aggregate recipe, or should I un-claim the issue?

**Comment by vishalsodani** [comment]
I would like to do the aggregate recipe. What would you like to see in this recipe ? Count(*) , max ?

**Comment by AndyGauge** [comment]
How about sort authors by number of books?

**Comment by vishalsodani** [comment]
> How about sort authors by number of books?

ok. The insert recipe did not show inserting data into the Book table. So, should I start by showing inserting data into the Book table and the do the sort query?

**Comment by KappaDistributive** [comment]
Are there any other recipes that we would like to add to the Postgres section?

**Comment by AndyGauge** [comment]
I'm closing this issue, if new postgres ideas come up we can open new issues.  Thanks!
