### ISSUE TITLE
Bump reqwest to 0.9

### ISSUE THREAD

**Issue by lnicola** [rust-lang-nursery/rust-cookbook#459]
`reqwest 0.9` was recently released, using `hyper 0.12`. A couple of examples need to be updated because of the header changes. It should also help with `openssl` compatibility -- I can't build the examples because of a version mismatch.

I'll try to work on this.

**Comment by AndyGauge** [comment]
I've been watching hyper::headers and I don't think this is ready.

**Comment by AndyGauge** [comment]
actually, I"m going to close this in favor of https://github.com/rust-lang-nursery/rust-cookbook/issues/419

**Comment by lnicola** [comment]
From the currently-enabled examples, the hardest to port seems to be the partial downloads one.

**Comment by AndyGauge** [comment]
I guess you are right about the enabled issues moving to 0.9, I was thinking about just the header examples.  I reopened this.  My bad.

**Comment by lnicola** [comment]
Closed by #460
