### ISSUE TITLE
crossbeam::Scope links are broken

### ISSUE THREAD

**Issue by JamesHinshelwood** [rust-lang-nursery/rust-cookbook#474]
It seems in 0.3 -> 0.4, crossbeam moved `Scope` from `crossbeam::Scope` to `crossbeam::thread::Scope`. Perhaps the advice to always use `*`s in links isn't the best - ideally we would have the link go to the latest semver compatible version, but for now we could just use the same version as we have in `Cargo.toml` and simply try to stay up to date with crate updates.

**Comment by AndyGauge** [comment]
Did the linkchecker catch it?

**Comment by JamesHinshelwood** [comment]
Yeah it did

**Comment by lnicola** [comment]
Fixed by #467.
