### ISSUE TITLE
Link Checker erroring in Travis CI

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#475]
0.03s$ ./ci/install_deps.sh
Running ./ci/install_deps.sh
Installing additional dependencies
pyenv: version `3.6' not installed
The command "./ci/install_deps.sh" failed and exited with 1 during .
Your build has been stopped.

**Comment by lnicola** [comment]
Can we RIIR `link-checker`? A couple of days ago I almost fell asleep waiting for it to run.

**Comment by AndyGauge** [comment]
Sure, but it is not a CPU bound problem, but an IO bound problem.
