### ISSUE TITLE
'Vector Sum' 'Vector norm calculation' links broken

### ISSUE THREAD

**Issue by pduzinki** [rust-lang-nursery/rust-cookbook#479]
'Vector Sum' 'Vector norm calculation' in Science sections are broken (error 404). I cannot found those recipes in book, tough source code can be found in repository. I believe that they should be added, but not sure where.

**Comment by JamesHinshelwood** [comment]
Will be fixed by #478

**Comment by pduzinki** [comment]
It won't be fixed with #478, since that PR only fixes broken links to visible chapters. 'Vector sum' and 'Vector norm calculation' are not visible in the book right now, though proper .md files are in src directory. I could make a PR adding them, but I'm not sure where should it be placed (either 'Mathematics' chapter, or maybe create 'Linear algebra' subchapter )

**Comment by JamesHinshelwood** [comment]
Vector sum and norm were added after I made the PR. I just need to rebase.

**Comment by JamesHinshelwood** [comment]
Fixed by #473

**Comment by AndyGauge** [comment]
I'm closing, I think this is resolved now. (currently resolved)
