### ISSUE TITLE
SQLite unused id

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#488]
test initialization_sect_create_a_sqlite_database_line_10 ... ok
warning: field is never used: `id`
 --> /tmp/rust-skeptic.1Pj6bBl4LxO2/test.rs:8:5
  |
8 |     id: i32,
  |     ^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

**Comment by lnicola** [comment]
Is this in my recipe? There's no `id` field there.
