### ISSUE TITLE
deprecation warning for errorchain

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#513]
warning: use of deprecated item 'std::error::Error::cause': replaced by Error::source, which can support downcasting
  --> /tmp/rust-skeptic.7Rpc9Z7uvsuK/test.rs:13:1
   |
13 | / error_chain! {
14 | |    foreign_links {
15 | |        CsvError(csv::Error);
16 | |        ParseInt(std::num::ParseIntError);
...  |
20 | |    }
21 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

**Comment by vityafx** [comment]
Related to: https://github.com/rust-lang-nursery/error-chain/issues/254

**Comment by AndyGauge** [comment]
https://users.rust-lang.org/t/error-chain-is-no-longer-maintained/27561
This would be a big change for the cookbook.

**Comment by AndyGauge** [comment]
https://crates.io/crates/error-chain/0.12.1
