### ISSUE TITLE
Cookbook examples for uuid

### ISSUE THREAD

**Issue by kinggoesgaming** [rust-lang-nursery/rust-cookbook#523]
Come up with ideas for nice introductory examples of using` uuid`, if need be showing in combination with other crates, that would be good to show in the Rust Cookbook. Leave your ideas here. PRs with example welcome.

**Comment by AndyGauge** [comment]
In issue #434 we decided that `uuid` was a bit esoteric and the use case was already well documented.  What the cookbook wants to solve is universal problems for many developers showing real world examples.
