### ISSUE TITLE
Salt and hash a password with PBKDF2 compliation error

### ISSUE THREAD

**Issue by subodhu** [rust-lang-nursery/rust-cookbook#529]
The code in section [Salt and hash a password with PBKDF2](https://rust-lang-nursery.github.io/rust-cookbook/cryptography/encryption.html#salt-and-hash-a-password-with-pbkdf2) results in compilation error.
Here is the errot

```
error[E0308]: mismatched types
  --> src/main.rs:21:9
   |
21 |         N_ITER,
   |         ^^^^^^ expected struct `std::num::NonZeroU32`, found u32
   |
   = note: expected type `std::num::NonZeroU32`
              found type `u32`

error[E0308]: mismatched types
  --> src/main.rs:31:9
   |
31 |         N_ITER,
   |         ^^^^^^ expected struct `std::num::NonZeroU32`, found u32
   |
   = note: expected type `std::num::NonZeroU32`
              found type `u32`

error[E0308]: mismatched types
  --> src/main.rs:39:9
   |
39 |         N_ITER,
   |         ^^^^^^ expected struct `std::num::NonZeroU32`, found u32
   |
   = note: expected type `std::num::NonZeroU32`
              found type `u32`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `pbkdf2`.

To learn more, run the command again with --verbose.
```

**Comment by AndyGauge** [comment]
Adding `use std::num::NonZeroU32` towards the top and changing `const N_ITER: u32 = 100_000;` to `const N_ITER: NonZeroU32 = 100_000;` should fix this.

**Comment by devMYC** [comment]
@AndyGauge it didn't work for me

```
error[E0308]: mismatched types
  --> src/main.rs:56:30
   |
56 |   const N_ITER: NonZeroU32 = 100_000u32;
   |                              ^^^^^^^^^^ expected struct `std::num::NonZeroU32`, found u32
   |
   = note: expected type `std::num::NonZeroU32`
              found type `u32`
```

And if you do this `const N_ITER: NonZeroU32 = NonZeroU32::new(100_000u32).unwrap();`, you'll get another error

```
error[E0015]: calls in constants are limited to tuple structs and tuple variants
  --> src/main.rs:56:30
   |
56 |   const N_ITER: NonZeroU32 = NonZeroU32::new(100_000u32).unwrap();
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: a limited form of compile-time function evaluation is available on a nightly compiler via `const fn`
```

My solution is to use `let n_iter = NonZeroU32::new(100_000u32).unwrap();` and replace `N_ITER` with `n_iter`. Not really sure if that's the correct way to solve the problem tho.

**Comment by AndyGauge** [comment]
How about`.new_unchecked(100_000u32)`  The cookbook tries to emphasize not using unwrap.  This is an example where obviously the static value is not zero, however, `.new_unchecked` is there for this sort of static assignment.

**Comment by subodhu** [comment]
It does work with `new_unchecked` if I upgrade the ring version to latest and it is also unsafe function. If it's OK, I'll send the pull request.

**Comment by evitalis** [comment]
Anymore thoughts on this? I have been using similar code to #538 but wondering if there is a more recommended way based on discussion in this thread. Would it also be safe to include #537 in whatever ends up happening here?
