### ISSUE TITLE
Update examples to 2018 edition

### ISSUE THREAD

**Issue by pickfire** [rust-lang-nursery/rust-cookbook#530]

**Comment by AndyGauge** [comment]
Yes, please!

**Comment by prabhat99** [comment]
What can I do to contribute to this problem?

**Comment by AndyGauge** [comment]
The work is complete, if you would like to review the PR for anything that might trip somebody up using it that would be helpful.  Go https://github.com/rust-lang-nursery/rust-cookbook/pull/565/files and click review

**Comment by pickfire** [comment]
@prabhat99 Reviewing the patch https://github.com/rust-lang-nursery/rust-cookbook/pull/565 would be nice.
