### ISSUE TITLE
Some missing crate information on 3.1, "Decompress a tarball... prefix... paths"

### ISSUE THREAD

**Issue by gkm2164** [rust-lang-nursery/rust-cookbook#546]
Hi, I love this cookbook, and I feel fun with typing it on my vim screen :)
Thank you.

By the way, although the example shows a code which uses 'flate2' and 'tar' library, the code can't be compiled without "error_chain" crate. I found the problem by clicking the "expand" icon and could access the full source codes.

It would be better if "error_chain" crate is specified explicitly(and also #[macro_use] is important one), and add some comment about it to avoid confusion to the beginner, or some description which informs reader to click the "expand" icon to get a whole working code.

Thanks!

**Comment by AndyGauge** [comment]
Glad you love the book.  

It's a valid point.  Towards the beginning of the book https://rust-lang-nursery.github.io/rust-cookbook/about.html#a-note-about-error-handling the expansion is discussed, but it is way overlooked.  Who wants to read an about section anyway?  Most people coming in will be heading for the good stuff--recipes that help them accomplish a task.  I'm going to move your comment to the comment section of issue #502 

Thanks for sharing!
