### ISSUE TITLE
AnsiTerm has a bad link

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#566]

**Comment by AndyGauge** [comment]
https://rust-lang-nursery.github.io/rust-cookbook/cli/ansi_terminal.html
 [ansi_term]:

**Comment by kimstacy** [comment]
@AndyGauge I noticed that the first occurrence of `crate` is also part of the hyperlink. 

I checked against other chapters to see what style was preferred, and noticed that `crate` is used differently [here](https://rust-lang-nursery.github.io/rust-cookbook/science/mathematics/linear_algebra.html#vector-comparison).

Would you also like `crate` to be unlinked in ANSI Terminal?

**Comment by kimstacy** [comment]
Also:  

Would you like `log` and `env_logger` in [Log Messages](https://rust-lang-nursery.github.io/rust-cookbook/development_tools/debugging/log.html) to link to crates.io's [log](https://crates.io/crates/log) and [env_logger](https://crates.io/crates/env_logger)?

I wasn't sure if you preferred both to be left alone, or if you had an alternative suggestion in mind. 

Your input would be much appreciated!

**Comment by AndyGauge** [comment]
Hey @kimstacy Thanks for the investigation.  If you look at https://rust-lang-nursery.github.io/rust-cookbook/intro.html you can see that all the 'badges' link to the crate docs.  The Log messages link you sent me I only see log and env_logger as badge links.  I might have otherwise missed what you are calling out, but badges should link to docs.  

In ansi_term, the link "`ansi_term` crate" text is OK.  It directs to crates.io and that may not be convention, but the recipe author chose to do it that way, and it was approved.  Just below that there is "[`ansi_term`]:" which markdown detects as text:link with the link being nothing.  If you remove that colon, everything should work.  This Issue is really the removal of one character, the colon.
