### ISSUE TITLE
Image host has an expired SSL certificate

### ISSUE THREAD

**Issue by raymondsiu** [rust-lang-nursery/rust-cookbook#568]
Image links on the Rust Book page are all broken due to the expired SSL certificate on the host.

Observed at URL: https://rust-lang-nursery.github.io/rust-cookbook/intro.html

Sample of the error: `GET https://badge-cache.kominick.com/crates/v/rand.svg?label=rand net::ERR_CERT_DATE_INVALID`

Certificate Dates:
```
Issued On	Tuesday, 15 October 2019 at 09:43:53
Expires On	Monday, 13 January 2020 at 08:43:53
```

**Comment by AndyGauge** [comment]
yikes.  I'm not even sure who offered to maintain that cache.  I know we started using it because load times were long.

**Comment by AndyGauge** [comment]
@jaemk do you know about this?

**Comment by jaemk** [comment]
yikes -- looking now, certman appears to have forgotten about this service

**Comment by jaemk** [comment]
Should be fixed now! Sorry about that - something must have gone wonky in my cluster.

**Comment by raymondsiu** [comment]
Looks good now!

**Comment by AndyGauge** [comment]
Thank you!
