### ISSUE TITLE
 type annotations needed

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#569]
error[E0282]: type annotations needed for `rusqlite::MappedRows<'_, [closure@/tmp/rust-skeptic.W3uKvyKglSl5/test.rs:41:42: 46:6]>`

  --> /tmp/rust-skeptic.W3uKvyKglSl5/test.rs:42:9

   |

41 |     let cats = stmt.query_map(NO_PARAMS, |row| {

   |         ---- consider giving `cats` the explicit type `rusqlite::MappedRows<'_, [closure@/tmp/rust-skeptic.W3uKvyKglSl5/test.rs:41:42: 46:6]>`, where the type parameter `E` is specified

42 |         Ok(Cat {

   |         ^^ cannot infer type for `E`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.

test insert_select_sect_insert_and_select_data_line_8 ... FAILED

**Comment by JOE1994** [comment]
I think this issue is resolved now after #582 was pushed to `master` 👍
