### ISSUE TITLE
reqwest examples are outdated

### ISSUE THREAD

**Issue by Belval** [rust-lang-nursery/rust-cookbook#571]
Since reqwest 0.10.1, it uses `async` by default, making most examples in the cookbook outdated.

I'll try and make a PR, but I do not think that have sufficient experience with the crate. I will also try to contact the project maintainers.

**Comment by AndyGauge** [comment]
Good point.  We really ought to do some async stuff now that crates are starting to apply the core implementation.

**Comment by swedebugia** [comment]
I suggest migrating the old examples to reqwest::blocking as soon as possible. It is an optional feature so it requires this line in the toml:
```reqwest = { version = "*", features = ["blocking"] } ```
I can prepare a pull request if you would like.

**Comment by samuela** [comment]
Yeah, the example here is outdated as `Response`s can no longer be `std::io::copy`d: https://github.com/rust-lang-nursery/rust-cookbook/blob/master/src/web/clients/download/basic.md
