### ISSUE TITLE
|  |  |

### ISSUE THREAD

**Issue by papac25** [rust-lang-nursery/rust-cookbook#613]
|  |  |
| ------------- | ------------- |
| Crates  | std,  crossbeam_channel |
| Section  | 4.3 Sharing data between threads  |

    - shared ownership with `Arc`
    - shared stack with `crossbeam`
 __

**Comment by stappersg** [comment]
@papac25 please elaborate on the why of this issue. Tell what it should achieve.   (Closing it is also fine.)
