### ISSUE TITLE
Pull requests pile up

### ISSUE THREAD

**Issue by stappersg** [rust-lang-nursery/rust-cookbook#646]
Down side of a pile of pull requests is that it might emit _stop sending PRs_.

Up side of a pile of pull requests is that it might emit _fresh team members wanted_.

**Comment by AndyGauge** [comment]
PSA: use github notifications, that little blue thing in the upper right and _unsubscribe_ from everything that isn't relevant.  Sorry about all the noise that got in the way.

**Comment by stappersg** [comment]
On Sat, Nov 30, 2024 at 09:46:39AM -0800, Andrew Gauger wrote:
> Closed #646 as completed.

Thanks for the catch-up, thanks for reducing the pile of pull requests.

And above all: Thanks for showing the world this project is still alive.


Groeten
Geert Stappers
-- 
Silence is hard to parse
