### ISSUE TITLE
Chapter 16.1 External Commands missing crate link - error-chain

### ISSUE THREAD

**Issue by Jaxelr** [rust-lang-nursery/rust-cookbook#648]
The first section of chapter 16.1 is missing the crate error-chain:

![image](https://user-images.githubusercontent.com/5913008/115808463-883de600-a3b8-11eb-90e6-bcad6cc400bf.png)

**Comment by Jaxelr** [comment]
So does section 2: Run an external command passing it stdin and check for an error code

**Comment by AndyGauge** [comment]
switched out to anyhow
