### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by kevinji** [rust-lang-nursery/rust-cookbook#681]
Seems like there hasn't been any activity for almost 2 years; has this repo been abandoned? Should the community fork it to keep it alive?

**Comment by blandger** [comment]
It would be good if repo owner assign several people as maintainers, to review pools requests and merge PRs.

**Comment by jamesgraves** [comment]
I've actually been working on a fork of this repo here:

https://github.com/jamesgraves/rust-cookbook

I've only gotten through about half of the examples, and have to convert the other half, even before adding a whole bunch more.

The [CHANGES.md](https://github.com/jamesgraves/rust-cookbook/blob/main/CHANGES.md) file explains what I've been going for.

I'd been sort of waiting until I finished with the conversion before approaching the current project maintainers (if they can even be contacted), but I am open to accepting help already.

There are bunches of examples that could be added (no particular order):

- tokio, async-std and related
- more database examples, including object databases, graph databases, BonsaiDB
- Raft Consensus library
- advanced data structures
- basic and advanced TCP/IP networking
- more with file system traversal
- zip files and other archives
- sound, graphics, game engines
- GTK, Qt, FLTK, Bevy + eGUI, other UI toolkits
- GPU processing, CUDA
- machine learning, Tensorflow
- high-performance computing: OpenMP, etc.
- network filesystems
- statistics, math, bignum libraries
- crypto, SSL, SSH, other public key encryption, X.509, RusTLS
- social media APIs
- personal file sharing: OwnCloud, etc.
- search engines
- AWS and other cloud services
- buffer pools, garbage collection, or other reference-counted examples
- IPv6 address processing
- authentication / authorization: Oauth2, LDAP/AD, DNS lookups
- cloud stuff: LB, status reporting (Vigil), routing, orchestration, containers
- version control: libgit2: clone, change branches, create commits, push, pull
- cargo & project integration via things like cargo-edit

The only limit is available free time...

**Comment by monqyClouds** [comment]
This is excellent @jamesgraves I am rookie rust developer myself but I am very willing to help in any way I can. I'm coming from backend api development with nodeTS background. Please let me know of any way I can be useful to this course.

**Comment by jamesgraves** [comment]
I will accept pull requests.  If you want to convert some existing samples, great. If you want to add a new one, also great.

For the existing examples, I was going in alphabetical order, and stopped before getting to `net`.

**Comment by alst2821** [comment]
Hi,
I'm adding a comment because I am glad to have found the version by jamesgraves,
https://github.com/jamesgraves/rust-cookbook 
because the example I was trying out 
https://jamesgraves.github.io/rust-cookbook/file/dir.html#find-all-png-files-recursively
did not work any more in the original.

**Comment by AndyGauge** [comment]
@jamesgraves do you want to help maintain the official one?  You work could benefit from the search traffic.

**Comment by jamesgraves** [comment]
Andrew Gauger ***@***.***> wrote:

> @jamesgraves <https://github.com/jamesgraves> do you want to help
> maintain the official one? You work could benefit from the search traffic.
>
> I was intending to ask to take over the project, but I haven't converted /
upgraded all the existing examples yet, so I was waiting. I'm actually
mostly done, except for the web request stuff, and giving everything
another proofread and edit.

If you all think it is in a good enough state as it is, I'd be glad to
merge all this into the official Cookbook repository.

All the examples I have converted are mostly up-to-date with current stable
versions of the libraries. However, changes to cargo update and cargo
upgrade now *don't* upgrade to a newer stable version of the crate that
possibly has breaking API changes. So there are some further updates needed
there.

I have made *extensive *changes though: with regards to how the examples
are presented, how they are implemented, and how everything is built and
run.  The CHANGES.md gives an overview:

https://github.com/jamesgraves/rust-cookbook/blob/main/CHANGES.md

I don't expect that everyone would agree that these changes are desirable,
so I was expecting there would be a lot of discussion about all that.

Let me know, I'd be glad to help.

**Comment by AndyGauge** [comment]
I have pulled both repositories and reviewed them since closing the issue.  I am saying that it is a lot to take in at once, and I'm trying to get the changes that contributors have made merged and deployed.  Please write up an issue with the recommendation to remove skeptic so we can get consensus.

**Comment by joshka** [comment]
https://github.com/rust-lang-nursery/rust-cookbook/issues/711
