### ISSUE TITLE
Dead links in Mathematics section

### ISSUE THREAD

**Issue by John-Nagle** [rust-lang-nursery/rust-cookbook#688]
Most of the links in the "Mathematics" section of https://rust-lang-nursery.github.io/rust-cookbook/ are dead.

I'd like to suggest adding  some library that has the small vectors you need for graphics - 2D, 3D, and 4D, along with the corresponding matrices.  Everybody doing graphics needs such a library. I'd suggest "glam", which is used by WGPU, a major graphics library, and Bevy, a game library. It has all the basic, routine operations on small vectors. 3 million downloads.

Then the Rust Playground, which uses the cookbook list, will include them. There are lots of little analytic geometry problems you can't run in the Playground, such as point to line, distance to rectangle, etc.

**Comment by AndyGauge** [comment]
I clicked around in Mathematics and didn't find the broken links, help me find the ones that need attention.

**Comment by John-Nagle** [comment]
Must have been fixed some time in the last year since the report. Closing.
